export type ScenarioTurn = {
  /** Who speaks this turn. The user always has at least one turn. */
  speaker: "npc" | "you";
  /** Chinese line — what the user should say (or hear the NPC say via TTS). */
  hanzi: string;
  pinyin: string;
  english: string;
};

export type Scenario = {
  id: string;
  title: string;
  emoji: string;
  hskLevel: number;
  minutes: number;
  blurb: string;
  setting: string;
  turns: ScenarioTurn[];
};

/**
 * Hand-curated scenarios grouped by HSK level. Each one is a short dialogue
 * around a single situation. Keep `setting` evocative — the trainer shows it
 * before the session so the user can imagine the scene. Aim for 5–10 turns
 * with the user speaking on at least 3 of them so Whisper has enough audio.
 */
export const SCENARIOS: Scenario[] = [
  // ────────────────────────────────────────────────────────────────────────
  // HSK 1 — first words, intros, ordering, family, numbers
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "greetings",
    title: "Greetings",
    emoji: "👋",
    hskLevel: 1,
    minutes: 2,
    blurb: "Say hello and introduce yourself.",
    setting: "You bump into a new classmate on the first day.",
    turns: [
      { speaker: "npc", hanzi: "你好！", pinyin: "Nǐ hǎo!", english: "Hello!" },
      { speaker: "you", hanzi: "你好！", pinyin: "Nǐ hǎo!", english: "Hello!" },
      { speaker: "npc", hanzi: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzi?", english: "What's your name?" },
      { speaker: "you", hanzi: "我叫李明。", pinyin: "Wǒ jiào Lǐ Míng.", english: "My name is Li Ming." },
      { speaker: "npc", hanzi: "很高兴认识你！", pinyin: "Hěn gāoxìng rènshi nǐ!", english: "Nice to meet you!" },
      { speaker: "you", hanzi: "我也是。", pinyin: "Wǒ yě shì.", english: "Me too." },
    ],
  },
  {
    id: "self-intro",
    title: "Self introduction",
    emoji: "🪪",
    hskLevel: 1,
    minutes: 2,
    blurb: "Tell someone where you're from and what you do.",
    setting: "Your new neighbor knocks on the door and says hi.",
    turns: [
      { speaker: "npc", hanzi: "你好，你是哪国人？", pinyin: "Nǐ hǎo, nǐ shì nǎ guó rén?", english: "Hi, what country are you from?" },
      { speaker: "you", hanzi: "我是美国人。", pinyin: "Wǒ shì Měiguó rén.", english: "I'm American." },
      { speaker: "npc", hanzi: "你做什么工作？", pinyin: "Nǐ zuò shénme gōngzuò?", english: "What do you do?" },
      { speaker: "you", hanzi: "我是学生。", pinyin: "Wǒ shì xuéshēng.", english: "I'm a student." },
      { speaker: "npc", hanzi: "你住在哪里？", pinyin: "Nǐ zhù zài nǎli?", english: "Where do you live?" },
      { speaker: "you", hanzi: "我住在三楼。", pinyin: "Wǒ zhù zài sān lóu.", english: "I live on the third floor." },
    ],
  },
  {
    id: "coffee",
    title: "Order coffee",
    emoji: "☕",
    hskLevel: 1,
    minutes: 2,
    blurb: "Buy a coffee at a café.",
    setting: "You walk into a busy Shanghai coffee shop.",
    turns: [
      { speaker: "npc", hanzi: "欢迎光临，您要什么？", pinyin: "Huānyíng guānglín, nín yào shénme?", english: "Welcome, what would you like?" },
      { speaker: "you", hanzi: "我要一杯咖啡。", pinyin: "Wǒ yào yì bēi kāfēi.", english: "I'd like one coffee." },
      { speaker: "npc", hanzi: "大杯还是小杯？", pinyin: "Dà bēi háishì xiǎo bēi?", english: "Large or small?" },
      { speaker: "you", hanzi: "大杯，谢谢。", pinyin: "Dà bēi, xièxie.", english: "Large, thanks." },
      { speaker: "npc", hanzi: "一共三十块。", pinyin: "Yīgòng sānshí kuài.", english: "That's thirty yuan total." },
      { speaker: "you", hanzi: "好的。", pinyin: "Hǎo de.", english: "Okay." },
    ],
  },
  {
    id: "buy-fruit",
    title: "Buy fruit",
    emoji: "🍎",
    hskLevel: 1,
    minutes: 2,
    blurb: "Pick up apples at the corner stand.",
    setting: "A small fruit stand on a busy street.",
    turns: [
      { speaker: "npc", hanzi: "您要什么？", pinyin: "Nín yào shénme?", english: "What would you like?" },
      { speaker: "you", hanzi: "我要苹果。", pinyin: "Wǒ yào píngguǒ.", english: "I'd like apples." },
      { speaker: "npc", hanzi: "要几个？", pinyin: "Yào jǐ ge?", english: "How many?" },
      { speaker: "you", hanzi: "五个。", pinyin: "Wǔ ge.", english: "Five." },
      { speaker: "npc", hanzi: "一共十块钱。", pinyin: "Yīgòng shí kuài qián.", english: "Ten yuan total." },
      { speaker: "you", hanzi: "给您。", pinyin: "Gěi nín.", english: "Here you go." },
    ],
  },
  {
    id: "in-class",
    title: "First day of class",
    emoji: "📚",
    hskLevel: 1,
    minutes: 2,
    blurb: "Greet the teacher and answer roll-call.",
    setting: "You walk into a Mandarin class on day one.",
    turns: [
      { speaker: "npc", hanzi: "你好，你是新同学吗？", pinyin: "Nǐ hǎo, nǐ shì xīn tóngxué ma?", english: "Hello, are you a new student?" },
      { speaker: "you", hanzi: "是的，我是新同学。", pinyin: "Shì de, wǒ shì xīn tóngxué.", english: "Yes, I'm new." },
      { speaker: "npc", hanzi: "你叫什么？", pinyin: "Nǐ jiào shénme?", english: "What's your name?" },
      { speaker: "you", hanzi: "我叫王小红。", pinyin: "Wǒ jiào Wáng Xiǎohóng.", english: "I'm Wang Xiaohong." },
      { speaker: "npc", hanzi: "好，请坐。", pinyin: "Hǎo, qǐng zuò.", english: "Good, please sit down." },
      { speaker: "you", hanzi: "谢谢老师。", pinyin: "Xièxie lǎoshī.", english: "Thank you, teacher." },
    ],
  },
  {
    id: "family-photo",
    title: "Talk about family",
    emoji: "👨‍👩‍👧",
    hskLevel: 1,
    minutes: 2,
    blurb: "Show a friend a photo of your family.",
    setting: "A friend asks about a photo on your phone.",
    turns: [
      { speaker: "npc", hanzi: "这是谁？", pinyin: "Zhè shì shéi?", english: "Who's this?" },
      { speaker: "you", hanzi: "这是我妈妈。", pinyin: "Zhè shì wǒ māma.", english: "This is my mom." },
      { speaker: "npc", hanzi: "她是老师吗？", pinyin: "Tā shì lǎoshī ma?", english: "Is she a teacher?" },
      { speaker: "you", hanzi: "不是，她是医生。", pinyin: "Bú shì, tā shì yīshēng.", english: "No, she's a doctor." },
      { speaker: "npc", hanzi: "你有哥哥吗？", pinyin: "Nǐ yǒu gēge ma?", english: "Do you have an older brother?" },
      { speaker: "you", hanzi: "我有一个哥哥。", pinyin: "Wǒ yǒu yí ge gēge.", english: "I have one older brother." },
    ],
  },
  {
    id: "what-time",
    title: "Ask the time",
    emoji: "⏰",
    hskLevel: 1,
    minutes: 2,
    blurb: "Ask a stranger for the time.",
    setting: "You're on the way to class and your phone died.",
    turns: [
      { speaker: "you", hanzi: "请问，现在几点？", pinyin: "Qǐng wèn, xiànzài jǐ diǎn?", english: "Excuse me, what time is it?" },
      { speaker: "npc", hanzi: "现在八点半。", pinyin: "Xiànzài bā diǎn bàn.", english: "It's eight-thirty." },
      { speaker: "you", hanzi: "谢谢你！", pinyin: "Xièxie nǐ!", english: "Thank you!" },
      { speaker: "npc", hanzi: "不客气。", pinyin: "Bú kèqi.", english: "You're welcome." },
    ],
  },
  {
    id: "say-goodbye",
    title: "Say goodbye",
    emoji: "🚪",
    hskLevel: 1,
    minutes: 2,
    blurb: "Wrap up an evening with a friend.",
    setting: "It's late and you're heading home from a friend's place.",
    turns: [
      { speaker: "you", hanzi: "我要回家了。", pinyin: "Wǒ yào huí jiā le.", english: "I'm going home." },
      { speaker: "npc", hanzi: "这么早？", pinyin: "Zhème zǎo?", english: "So early?" },
      { speaker: "you", hanzi: "明天我有课。", pinyin: "Míngtiān wǒ yǒu kè.", english: "I have class tomorrow." },
      { speaker: "npc", hanzi: "好，明天见。", pinyin: "Hǎo, míngtiān jiàn.", english: "Okay, see you tomorrow." },
      { speaker: "you", hanzi: "再见！", pinyin: "Zàijiàn!", english: "Bye!" },
    ],
  },
  {
    id: "how-old",
    title: "Birthday small talk",
    emoji: "🎂",
    hskLevel: 1,
    minutes: 2,
    blurb: "Tell a new friend your age and birthday.",
    setting: "You're at a get-together and someone asks how old you are.",
    turns: [
      { speaker: "npc", hanzi: "你今年多大？", pinyin: "Nǐ jīnnián duō dà?", english: "How old are you this year?" },
      { speaker: "you", hanzi: "我今年二十五岁。", pinyin: "Wǒ jīnnián èrshíwǔ suì.", english: "I'm twenty-five." },
      { speaker: "npc", hanzi: "你的生日是几月几号？", pinyin: "Nǐ de shēngrì shì jǐ yuè jǐ hào?", english: "When is your birthday?" },
      { speaker: "you", hanzi: "六月十二号。", pinyin: "Liù yuè shí'èr hào.", english: "June 12th." },
      { speaker: "npc", hanzi: "我也是六月！", pinyin: "Wǒ yě shì liù yuè!", english: "Mine's also June!" },
      { speaker: "you", hanzi: "真巧！", pinyin: "Zhēn qiǎo!", english: "What a coincidence!" },
    ],
  },
  {
    id: "phone-number",
    title: "Exchange numbers",
    emoji: "📱",
    hskLevel: 1,
    minutes: 2,
    blurb: "Trade phone numbers with a new friend.",
    setting: "After a class you want to keep in touch.",
    turns: [
      { speaker: "you", hanzi: "你的电话号码是多少？", pinyin: "Nǐ de diànhuà hàomǎ shì duōshǎo?", english: "What's your phone number?" },
      { speaker: "npc", hanzi: "138 1234 5678。", pinyin: "Yāo sān bā, yāo èr sān sì, wǔ liù qī bā.", english: "138 1234 5678." },
      { speaker: "you", hanzi: "我打电话给你。", pinyin: "Wǒ dǎ diànhuà gěi nǐ.", english: "I'll call you." },
      { speaker: "npc", hanzi: "好的，再见！", pinyin: "Hǎo de, zàijiàn!", english: "Okay, bye!" },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // HSK 2 — directions, transport, eating out, weather, plans
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "directions",
    title: "Ask directions",
    emoji: "🧭",
    hskLevel: 2,
    minutes: 3,
    blurb: "Find the metro station.",
    setting: "You're lost in Beijing and need the nearest subway.",
    turns: [
      { speaker: "you", hanzi: "请问，地铁站在哪里？", pinyin: "Qǐngwèn, dìtiě zhàn zài nǎli?", english: "Excuse me, where's the metro station?" },
      { speaker: "npc", hanzi: "一直往前走。", pinyin: "Yìzhí wǎng qián zǒu.", english: "Go straight ahead." },
      { speaker: "you", hanzi: "远吗？", pinyin: "Yuǎn ma?", english: "Is it far?" },
      { speaker: "npc", hanzi: "不远，大概五分钟。", pinyin: "Bù yuǎn, dàgài wǔ fēnzhōng.", english: "Not far, about five minutes." },
      { speaker: "you", hanzi: "谢谢你。", pinyin: "Xièxie nǐ.", english: "Thank you." },
    ],
  },
  {
    id: "restaurant",
    title: "At the restaurant",
    emoji: "🥟",
    hskLevel: 2,
    minutes: 3,
    blurb: "Order dumplings and water.",
    setting: "You sit down at a small noodle shop.",
    turns: [
      { speaker: "npc", hanzi: "几位？", pinyin: "Jǐ wèi?", english: "How many people?" },
      { speaker: "you", hanzi: "两位。", pinyin: "Liǎng wèi.", english: "Two." },
      { speaker: "npc", hanzi: "您要什么？", pinyin: "Nín yào shénme?", english: "What would you like?" },
      { speaker: "you", hanzi: "一份饺子，两杯水。", pinyin: "Yí fèn jiǎozi, liǎng bēi shuǐ.", english: "One dumplings, two waters." },
      { speaker: "npc", hanzi: "好的，请等一下。", pinyin: "Hǎo de, qǐng děng yíxià.", english: "Okay, please wait." },
      { speaker: "you", hanzi: "谢谢。", pinyin: "Xièxie.", english: "Thanks." },
    ],
  },
  {
    id: "taxi",
    title: "Take a taxi",
    emoji: "🚕",
    hskLevel: 2,
    minutes: 2,
    blurb: "Tell the driver where to go.",
    setting: "You flag down a cab outside the airport.",
    turns: [
      { speaker: "npc", hanzi: "您去哪儿？", pinyin: "Nín qù nǎr?", english: "Where to?" },
      { speaker: "you", hanzi: "我去机场。", pinyin: "Wǒ qù jīchǎng.", english: "I'm going to the airport." },
      { speaker: "npc", hanzi: "您赶时间吗？", pinyin: "Nín gǎn shíjiān ma?", english: "Are you in a hurry?" },
      { speaker: "you", hanzi: "有一点。", pinyin: "Yǒu yìdiǎn.", english: "A little." },
      { speaker: "npc", hanzi: "二十分钟就到。", pinyin: "Èrshí fēnzhōng jiù dào.", english: "We'll be there in twenty minutes." },
      { speaker: "you", hanzi: "谢谢！", pinyin: "Xièxie!", english: "Thanks!" },
    ],
  },
  {
    id: "weather-chat",
    title: "Weather chat",
    emoji: "🌤️",
    hskLevel: 2,
    minutes: 2,
    blurb: "Comment on today's weather.",
    setting: "Standing in line at a café in winter.",
    turns: [
      { speaker: "npc", hanzi: "今天真冷！", pinyin: "Jīntiān zhēn lěng!", english: "It's really cold today!" },
      { speaker: "you", hanzi: "是啊，外面下雪了。", pinyin: "Shì a, wàimian xià xuě le.", english: "Yeah, it's snowing outside." },
      { speaker: "npc", hanzi: "你冷不冷？", pinyin: "Nǐ lěng bù lěng?", english: "Are you cold?" },
      { speaker: "you", hanzi: "有点儿冷。", pinyin: "Yǒudiǎnr lěng.", english: "A bit cold." },
      { speaker: "npc", hanzi: "明天会更冷。", pinyin: "Míngtiān huì gèng lěng.", english: "Tomorrow will be colder." },
      { speaker: "you", hanzi: "我要多穿一点。", pinyin: "Wǒ yào duō chuān yìdiǎn.", english: "I need to wear more layers." },
    ],
  },
  {
    id: "doctor-cold",
    title: "Visit the doctor",
    emoji: "🤒",
    hskLevel: 2,
    minutes: 3,
    blurb: "Describe your symptoms.",
    setting: "Small clinic, you've had a cold for two days.",
    turns: [
      { speaker: "npc", hanzi: "你哪里不舒服？", pinyin: "Nǐ nǎli bù shūfu?", english: "What's wrong?" },
      { speaker: "you", hanzi: "我头疼，还咳嗽。", pinyin: "Wǒ tóu téng, hái késòu.", english: "I have a headache and a cough." },
      { speaker: "npc", hanzi: "几天了？", pinyin: "Jǐ tiān le?", english: "For how many days?" },
      { speaker: "you", hanzi: "两天了。", pinyin: "Liǎng tiān le.", english: "Two days." },
      { speaker: "npc", hanzi: "多喝水，多休息。", pinyin: "Duō hē shuǐ, duō xiūxi.", english: "Drink lots of water and rest." },
      { speaker: "you", hanzi: "好的，谢谢医生。", pinyin: "Hǎo de, xièxie yīshēng.", english: "Okay, thanks doctor." },
    ],
  },
  {
    id: "hotel-checkin",
    title: "Hotel check-in",
    emoji: "🏨",
    hskLevel: 2,
    minutes: 3,
    blurb: "Check in to your room.",
    setting: "You arrive at a small hotel in Hangzhou.",
    turns: [
      { speaker: "npc", hanzi: "您好，请问您订房间了吗？", pinyin: "Nín hǎo, qǐng wèn nín dìng fángjiān le ma?", english: "Hello, did you book a room?" },
      { speaker: "you", hanzi: "订了，我姓张。", pinyin: "Dìng le, wǒ xìng Zhāng.", english: "Yes, my surname is Zhang." },
      { speaker: "npc", hanzi: "您住几天？", pinyin: "Nín zhù jǐ tiān?", english: "How many nights?" },
      { speaker: "you", hanzi: "三天。", pinyin: "Sān tiān.", english: "Three nights." },
      { speaker: "npc", hanzi: "请给我您的护照。", pinyin: "Qǐng gěi wǒ nín de hùzhào.", english: "Please give me your passport." },
      { speaker: "you", hanzi: "给您。", pinyin: "Gěi nín.", english: "Here you are." },
    ],
  },
  {
    id: "supermarket",
    title: "Find an item",
    emoji: "🛒",
    hskLevel: 2,
    minutes: 2,
    blurb: "Ask where things are in the supermarket.",
    setting: "You can't find soy sauce in a big supermarket.",
    turns: [
      { speaker: "you", hanzi: "请问，酱油在哪里？", pinyin: "Qǐng wèn, jiàngyóu zài nǎli?", english: "Excuse me, where's the soy sauce?" },
      { speaker: "npc", hanzi: "在那边，第二排。", pinyin: "Zài nà biān, dì èr pái.", english: "Over there, second aisle." },
      { speaker: "you", hanzi: "谢谢！", pinyin: "Xièxie!", english: "Thanks!" },
      { speaker: "npc", hanzi: "还需要别的吗？", pinyin: "Hái xūyào bié de ma?", english: "Anything else you need?" },
      { speaker: "you", hanzi: "不用了，谢谢。", pinyin: "Bú yòng le, xièxie.", english: "No thanks." },
    ],
  },
  {
    id: "phone-call",
    title: "Call a friend",
    emoji: "📞",
    hskLevel: 2,
    minutes: 2,
    blurb: "Phone a friend to make plans.",
    setting: "You want to grab lunch with a classmate.",
    turns: [
      { speaker: "npc", hanzi: "喂，你好。", pinyin: "Wèi, nǐ hǎo.", english: "Hello?" },
      { speaker: "you", hanzi: "喂，是小王吗？", pinyin: "Wèi, shì Xiǎo Wáng ma?", english: "Hi, is this Xiao Wang?" },
      { speaker: "npc", hanzi: "是我，什么事？", pinyin: "Shì wǒ, shénme shì?", english: "It's me, what's up?" },
      { speaker: "you", hanzi: "中午一起吃饭吗？", pinyin: "Zhōngwǔ yìqǐ chīfàn ma?", english: "Want to grab lunch?" },
      { speaker: "npc", hanzi: "好啊，几点？", pinyin: "Hǎo a, jǐ diǎn?", english: "Sure, what time?" },
      { speaker: "you", hanzi: "十二点，老地方。", pinyin: "Shí'èr diǎn, lǎo dìfāng.", english: "Noon, the usual place." },
    ],
  },
  {
    id: "weekend-plans",
    title: "Plan the weekend",
    emoji: "📅",
    hskLevel: 2,
    minutes: 3,
    blurb: "Decide what to do on Saturday.",
    setting: "Two friends chatting about Saturday plans.",
    turns: [
      { speaker: "npc", hanzi: "周末你想做什么？", pinyin: "Zhōumò nǐ xiǎng zuò shénme?", english: "What do you want to do this weekend?" },
      { speaker: "you", hanzi: "我想去看电影。", pinyin: "Wǒ xiǎng qù kàn diànyǐng.", english: "I want to go see a movie." },
      { speaker: "npc", hanzi: "看什么电影？", pinyin: "Kàn shénme diànyǐng?", english: "What movie?" },
      { speaker: "you", hanzi: "新的中国电影。", pinyin: "Xīn de Zhōngguó diànyǐng.", english: "A new Chinese film." },
      { speaker: "npc", hanzi: "几点开始？", pinyin: "Jǐ diǎn kāishǐ?", english: "What time does it start?" },
      { speaker: "you", hanzi: "晚上七点半。", pinyin: "Wǎnshang qī diǎn bàn.", english: "Seven-thirty in the evening." },
    ],
  },
  {
    id: "lost-wallet",
    title: "Lost something",
    emoji: "👛",
    hskLevel: 2,
    minutes: 3,
    blurb: "Report a lost wallet.",
    setting: "You realize your wallet is missing at a restaurant.",
    turns: [
      { speaker: "you", hanzi: "我的钱包不见了。", pinyin: "Wǒ de qiánbāo bú jiàn le.", english: "My wallet is missing." },
      { speaker: "npc", hanzi: "什么时候不见的？", pinyin: "Shénme shíhou bú jiàn de?", english: "When did it go missing?" },
      { speaker: "you", hanzi: "刚才在桌子上。", pinyin: "Gāngcái zài zhuōzi shàng.", english: "Just now, on the table." },
      { speaker: "npc", hanzi: "什么颜色的？", pinyin: "Shénme yánsè de?", english: "What color is it?" },
      { speaker: "you", hanzi: "黑色的。", pinyin: "Hēisè de.", english: "Black." },
      { speaker: "npc", hanzi: "我帮你找一下。", pinyin: "Wǒ bāng nǐ zhǎo yíxià.", english: "Let me help you look." },
    ],
  },
  {
    id: "buy-train-ticket",
    title: "Buy a train ticket",
    emoji: "🚆",
    hskLevel: 2,
    minutes: 3,
    blurb: "Get a high-speed train ticket.",
    setting: "Beijing South Station ticket counter.",
    turns: [
      { speaker: "you", hanzi: "我要去上海。", pinyin: "Wǒ yào qù Shànghǎi.", english: "I want to go to Shanghai." },
      { speaker: "npc", hanzi: "什么时候？", pinyin: "Shénme shíhou?", english: "When?" },
      { speaker: "you", hanzi: "明天上午。", pinyin: "Míngtiān shàngwǔ.", english: "Tomorrow morning." },
      { speaker: "npc", hanzi: "几点的？", pinyin: "Jǐ diǎn de?", english: "What time?" },
      { speaker: "you", hanzi: "九点的，一张票。", pinyin: "Jiǔ diǎn de, yì zhāng piào.", english: "Nine o'clock, one ticket." },
      { speaker: "npc", hanzi: "五百五十块。", pinyin: "Wǔbǎi wǔshí kuài.", english: "Five hundred fifty yuan." },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // HSK 3 — shopping, takeout, complaints, invitations, travel
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "shopping",
    title: "Shopping for clothes",
    emoji: "🛍️",
    hskLevel: 3,
    minutes: 4,
    blurb: "Try on clothes and ask about price.",
    setting: "You're browsing in a clothing store downtown.",
    turns: [
      { speaker: "npc", hanzi: "需要帮忙吗？", pinyin: "Xūyào bāngmáng ma?", english: "Need any help?" },
      { speaker: "you", hanzi: "我想看看这件衣服。", pinyin: "Wǒ xiǎng kànkan zhè jiàn yīfu.", english: "I'd like to look at this." },
      { speaker: "npc", hanzi: "您穿什么号？", pinyin: "Nín chuān shénme hào?", english: "What size do you wear?" },
      { speaker: "you", hanzi: "中号，谢谢。", pinyin: "Zhōng hào, xièxie.", english: "Medium, thanks." },
      { speaker: "npc", hanzi: "试衣间在那边。", pinyin: "Shì yī jiān zài nà biān.", english: "The fitting room is over there." },
      { speaker: "you", hanzi: "这件多少钱？", pinyin: "Zhè jiàn duōshǎo qián?", english: "How much is this?" },
      { speaker: "npc", hanzi: "两百块。", pinyin: "Liǎng bǎi kuài.", english: "Two hundred yuan." },
      { speaker: "you", hanzi: "可以便宜一点吗？", pinyin: "Kěyǐ piányi yìdiǎn ma?", english: "Can it be a little cheaper?" },
    ],
  },
  {
    id: "order-takeout",
    title: "Order takeout",
    emoji: "🥡",
    hskLevel: 3,
    minutes: 3,
    blurb: "Phone in a delivery order.",
    setting: "Calling your favorite restaurant from home.",
    turns: [
      { speaker: "npc", hanzi: "您好，您要点什么？", pinyin: "Nín hǎo, nín yào diǎn shénme?", english: "Hello, what would you like to order?" },
      { speaker: "you", hanzi: "我要一份宫保鸡丁。", pinyin: "Wǒ yào yí fèn gōngbǎo jīdīng.", english: "One Kung Pao chicken, please." },
      { speaker: "npc", hanzi: "要米饭吗？", pinyin: "Yào mǐfàn ma?", english: "Want rice?" },
      { speaker: "you", hanzi: "要两碗米饭。", pinyin: "Yào liǎng wǎn mǐfàn.", english: "Two bowls of rice." },
      { speaker: "npc", hanzi: "您的地址是？", pinyin: "Nín de dìzhǐ shì?", english: "What's your address?" },
      { speaker: "you", hanzi: "中山路五十号。", pinyin: "Zhōngshān lù wǔshí hào.", english: "50 Zhongshan Road." },
      { speaker: "npc", hanzi: "三十分钟到。", pinyin: "Sānshí fēnzhōng dào.", english: "Arrives in thirty minutes." },
    ],
  },
  {
    id: "complain-noise",
    title: "Noisy neighbor",
    emoji: "🔊",
    hskLevel: 3,
    minutes: 3,
    blurb: "Politely ask a neighbor to keep it down.",
    setting: "It's late and music keeps coming through the wall.",
    turns: [
      { speaker: "you", hanzi: "不好意思，打扰一下。", pinyin: "Bù hǎo yìsi, dǎrǎo yíxià.", english: "Sorry to bother you." },
      { speaker: "npc", hanzi: "什么事？", pinyin: "Shénme shì?", english: "What's up?" },
      { speaker: "you", hanzi: "声音有点儿大。", pinyin: "Shēngyīn yǒudiǎnr dà.", english: "The sound is a bit loud." },
      { speaker: "npc", hanzi: "真的吗？对不起。", pinyin: "Zhēn de ma? Duìbuqǐ.", english: "Really? I'm sorry." },
      { speaker: "you", hanzi: "可以小一点吗？", pinyin: "Kěyǐ xiǎo yìdiǎn ma?", english: "Could you turn it down?" },
      { speaker: "npc", hanzi: "马上小一点。", pinyin: "Mǎshàng xiǎo yìdiǎn.", english: "I'll turn it down right away." },
    ],
  },
  {
    id: "birthday-invite",
    title: "Birthday invite",
    emoji: "🎉",
    hskLevel: 3,
    minutes: 3,
    blurb: "Invite a friend to your birthday.",
    setting: "Catching up after class with a classmate.",
    turns: [
      { speaker: "you", hanzi: "周六是我的生日。", pinyin: "Zhōuliù shì wǒ de shēngrì.", english: "Saturday is my birthday." },
      { speaker: "npc", hanzi: "你有什么打算？", pinyin: "Nǐ yǒu shénme dǎsuàn?", english: "Any plans?" },
      { speaker: "you", hanzi: "我想请你来吃饭。", pinyin: "Wǒ xiǎng qǐng nǐ lái chīfàn.", english: "I'd like to invite you to dinner." },
      { speaker: "npc", hanzi: "太好了！几点？", pinyin: "Tài hǎo le! Jǐ diǎn?", english: "Great! What time?" },
      { speaker: "you", hanzi: "晚上六点，在我家。", pinyin: "Wǎnshang liù diǎn, zài wǒ jiā.", english: "Six in the evening at my place." },
      { speaker: "npc", hanzi: "我一定来。", pinyin: "Wǒ yídìng lái.", english: "I'll definitely come." },
    ],
  },
  {
    id: "lost-and-found",
    title: "Lost and found",
    emoji: "🧳",
    hskLevel: 3,
    minutes: 3,
    blurb: "Pick up a lost bag at the help desk.",
    setting: "Airport lost-and-found counter.",
    turns: [
      { speaker: "you", hanzi: "我把行李丢了。", pinyin: "Wǒ bǎ xíngli diū le.", english: "I lost my luggage." },
      { speaker: "npc", hanzi: "什么样的行李？", pinyin: "Shénme yàng de xíngli?", english: "What does it look like?" },
      { speaker: "you", hanzi: "蓝色的大箱子。", pinyin: "Lánsè de dà xiāngzi.", english: "A big blue suitcase." },
      { speaker: "npc", hanzi: "上面有标签吗？", pinyin: "Shàngmiàn yǒu biāoqiān ma?", english: "Is there a tag on it?" },
      { speaker: "you", hanzi: "有，是我的名字。", pinyin: "Yǒu, shì wǒ de míngzì.", english: "Yes, with my name." },
      { speaker: "npc", hanzi: "请您填一下表。", pinyin: "Qǐng nín tián yíxià biǎo.", english: "Please fill out a form." },
    ],
  },
  {
    id: "apartment-tour",
    title: "Apartment tour",
    emoji: "🏠",
    hskLevel: 3,
    minutes: 4,
    blurb: "Look at a place to rent.",
    setting: "An agent shows you a one-bedroom apartment.",
    turns: [
      { speaker: "npc", hanzi: "这是客厅，很大。", pinyin: "Zhè shì kètīng, hěn dà.", english: "This is the living room, very big." },
      { speaker: "you", hanzi: "卧室有几个？", pinyin: "Wòshì yǒu jǐ ge?", english: "How many bedrooms?" },
      { speaker: "npc", hanzi: "一个卧室，一个书房。", pinyin: "Yí ge wòshì, yí ge shūfáng.", english: "One bedroom and one study." },
      { speaker: "you", hanzi: "厨房在哪边？", pinyin: "Chúfáng zài nǎ biān?", english: "Where's the kitchen?" },
      { speaker: "npc", hanzi: "在那边，旁边是卫生间。", pinyin: "Zài nà biān, pángbiān shì wèishēngjiān.", english: "Over there, the bathroom's next to it." },
      { speaker: "you", hanzi: "房租多少？", pinyin: "Fángzū duōshǎo?", english: "How much is the rent?" },
      { speaker: "npc", hanzi: "一个月四千。", pinyin: "Yí ge yuè sì qiān.", english: "Four thousand a month." },
    ],
  },
  {
    id: "study-discussion",
    title: "Talk about study habits",
    emoji: "📖",
    hskLevel: 3,
    minutes: 3,
    blurb: "Compare how you both study.",
    setting: "Two students chatting in the library.",
    turns: [
      { speaker: "npc", hanzi: "你怎么学中文？", pinyin: "Nǐ zěnme xué Zhōngwén?", english: "How do you study Chinese?" },
      { speaker: "you", hanzi: "我每天看视频，读课文。", pinyin: "Wǒ měitiān kàn shìpín, dú kèwén.", english: "Every day I watch videos and read texts." },
      { speaker: "npc", hanzi: "你觉得难吗？", pinyin: "Nǐ juéde nán ma?", english: "Do you find it hard?" },
      { speaker: "you", hanzi: "有时候很难。", pinyin: "Yǒu shíhou hěn nán.", english: "Sometimes it's very hard." },
      { speaker: "npc", hanzi: "什么最难？", pinyin: "Shénme zuì nán?", english: "What's the hardest part?" },
      { speaker: "you", hanzi: "声调最难。", pinyin: "Shēngdiào zuì nán.", english: "The tones are hardest." },
    ],
  },
  {
    id: "gym-signup",
    title: "Sign up at the gym",
    emoji: "💪",
    hskLevel: 3,
    minutes: 3,
    blurb: "Get a gym membership.",
    setting: "Front desk of a downtown gym.",
    turns: [
      { speaker: "you", hanzi: "我想办一张会员卡。", pinyin: "Wǒ xiǎng bàn yì zhāng huìyuán kǎ.", english: "I'd like to sign up for a membership." },
      { speaker: "npc", hanzi: "您要哪种？", pinyin: "Nín yào nǎ zhǒng?", english: "Which type would you like?" },
      { speaker: "you", hanzi: "一年的，多少钱？", pinyin: "Yì nián de, duōshǎo qián?", english: "A one-year one — how much?" },
      { speaker: "npc", hanzi: "三千块，包括游泳。", pinyin: "Sān qiān kuài, bāokuò yóuyǒng.", english: "Three thousand, including the pool." },
      { speaker: "you", hanzi: "可以分期付款吗？", pinyin: "Kěyǐ fēnqī fùkuǎn ma?", english: "Can I pay in installments?" },
      { speaker: "npc", hanzi: "可以分三次。", pinyin: "Kěyǐ fēn sān cì.", english: "You can split it three ways." },
    ],
  },
  {
    id: "movie-after",
    title: "After the movie",
    emoji: "🎬",
    hskLevel: 3,
    minutes: 3,
    blurb: "Discuss a movie you just saw.",
    setting: "Walking out of the cinema with a friend.",
    turns: [
      { speaker: "npc", hanzi: "电影怎么样？", pinyin: "Diànyǐng zěnmeyàng?", english: "How was the movie?" },
      { speaker: "you", hanzi: "挺好看的。", pinyin: "Tǐng hǎokàn de.", english: "Pretty good." },
      { speaker: "npc", hanzi: "你最喜欢哪个角色？", pinyin: "Nǐ zuì xǐhuan nǎ ge juésè?", english: "Which character did you like most?" },
      { speaker: "you", hanzi: "那个老人，他很有意思。", pinyin: "Nà ge lǎorén, tā hěn yǒu yìsi.", english: "The old man — he was really interesting." },
      { speaker: "npc", hanzi: "结尾你看懂了吗？", pinyin: "Jiéwěi nǐ kàn dǒng le ma?", english: "Did you understand the ending?" },
      { speaker: "you", hanzi: "没完全懂。", pinyin: "Méi wánquán dǒng.", english: "Not completely." },
    ],
  },
  {
    id: "give-directions",
    title: "Give directions",
    emoji: "📍",
    hskLevel: 3,
    minutes: 3,
    blurb: "Help a tourist find a museum.",
    setting: "A tourist stops you on the street.",
    turns: [
      { speaker: "npc", hanzi: "请问博物馆怎么走？", pinyin: "Qǐng wèn bówùguǎn zěnme zǒu?", english: "How do I get to the museum?" },
      { speaker: "you", hanzi: "您往前走，过两个红绿灯。", pinyin: "Nín wǎng qián zǒu, guò liǎng ge hónglǜdēng.", english: "Go straight, past two traffic lights." },
      { speaker: "npc", hanzi: "然后呢？", pinyin: "Ránhòu ne?", english: "Then?" },
      { speaker: "you", hanzi: "在右边，旁边有一个公园。", pinyin: "Zài yòu biān, pángbiān yǒu yí ge gōngyuán.", english: "On the right, next to a park." },
      { speaker: "npc", hanzi: "走路要多长时间？", pinyin: "Zǒu lù yào duō cháng shíjiān?", english: "How long does it take to walk?" },
      { speaker: "you", hanzi: "差不多十五分钟。", pinyin: "Chàbuduō shíwǔ fēnzhōng.", english: "About fifteen minutes." },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // HSK 4 — work, relationships, deeper opinions, problems
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "job-interview",
    title: "Job interview",
    emoji: "💼",
    hskLevel: 4,
    minutes: 5,
    blurb: "Answer questions at a tech interview.",
    setting: "First-round interview for a junior developer role.",
    turns: [
      { speaker: "npc", hanzi: "请简单介绍一下自己。", pinyin: "Qǐng jiǎndān jièshào yíxià zìjǐ.", english: "Please briefly introduce yourself." },
      { speaker: "you", hanzi: "我做了三年的程序员，主要做后端。", pinyin: "Wǒ zuò le sān nián de chéngxùyuán, zhǔyào zuò hòuduān.", english: "I've been a developer for three years, mostly backend." },
      { speaker: "npc", hanzi: "你为什么想换工作？", pinyin: "Nǐ wèishénme xiǎng huàn gōngzuò?", english: "Why are you looking to change jobs?" },
      { speaker: "you", hanzi: "我想找新的挑战。", pinyin: "Wǒ xiǎng zhǎo xīn de tiǎozhàn.", english: "I want a new challenge." },
      { speaker: "npc", hanzi: "你的优点是什么？", pinyin: "Nǐ de yōudiǎn shì shénme?", english: "What are your strengths?" },
      { speaker: "you", hanzi: "我学得很快，而且很认真。", pinyin: "Wǒ xué de hěn kuài, érqiě hěn rènzhēn.", english: "I learn quickly and I'm thorough." },
      { speaker: "npc", hanzi: "你期望多少工资？", pinyin: "Nǐ qīwàng duōshǎo gōngzī?", english: "What salary do you expect?" },
      { speaker: "you", hanzi: "可以聊一下。", pinyin: "Kěyǐ liáo yíxià.", english: "We can discuss it." },
    ],
  },
  {
    id: "rent-negotiation",
    title: "Negotiate rent",
    emoji: "🤝",
    hskLevel: 4,
    minutes: 4,
    blurb: "Talk down the rent on an apartment.",
    setting: "Sitting with the landlord after the tour.",
    turns: [
      { speaker: "npc", hanzi: "这个价格已经很合理了。", pinyin: "Zhège jiàgé yǐjīng hěn hélǐ le.", english: "This price is already very reasonable." },
      { speaker: "you", hanzi: "我觉得有点儿贵。", pinyin: "Wǒ juéde yǒudiǎnr guì.", english: "I feel it's a bit expensive." },
      { speaker: "npc", hanzi: "您觉得多少合适？", pinyin: "Nín juéde duōshǎo héshì?", english: "What price do you have in mind?" },
      { speaker: "you", hanzi: "三千八，我可以马上签合同。", pinyin: "Sān qiān bā, wǒ kěyǐ mǎshàng qiān hétóng.", english: "3,800, and I'll sign right away." },
      { speaker: "npc", hanzi: "三千九怎么样？", pinyin: "Sān qiān jiǔ zěnmeyàng?", english: "How about 3,900?" },
      { speaker: "you", hanzi: "好，那就这么定了。", pinyin: "Hǎo, nà jiù zhème dìng le.", english: "Okay, deal." },
    ],
  },
  {
    id: "customer-service",
    title: "Customer service call",
    emoji: "📲",
    hskLevel: 4,
    minutes: 4,
    blurb: "Complain about a delayed package.",
    setting: "Phone support of an online store.",
    turns: [
      { speaker: "npc", hanzi: "您好，请问有什么问题？", pinyin: "Nín hǎo, qǐng wèn yǒu shénme wèntí?", english: "Hello, how can I help?" },
      { speaker: "you", hanzi: "我的包裹一周还没到。", pinyin: "Wǒ de bāoguǒ yì zhōu hái méi dào.", english: "My package hasn't arrived in a week." },
      { speaker: "npc", hanzi: "请告诉我订单号。", pinyin: "Qǐng gàosu wǒ dìngdān hào.", english: "Please tell me the order number." },
      { speaker: "you", hanzi: "12345678。", pinyin: "Yāo èr sān sì wǔ liù qī bā.", english: "12345678." },
      { speaker: "npc", hanzi: "我帮您查一下。", pinyin: "Wǒ bāng nín chá yíxià.", english: "Let me check for you." },
      { speaker: "you", hanzi: "我希望尽快解决。", pinyin: "Wǒ xīwàng jǐnkuài jiějué.", english: "I'd like this resolved soon." },
      { speaker: "npc", hanzi: "我们今天给您发新的。", pinyin: "Wǒmen jīntiān gěi nín fā xīn de.", english: "We'll send a replacement today." },
    ],
  },
  {
    id: "first-date-cafe",
    title: "Coffee date",
    emoji: "💞",
    hskLevel: 4,
    minutes: 4,
    blurb: "First date small-talk at a café.",
    setting: "Saturday afternoon at an indie coffee shop.",
    turns: [
      { speaker: "npc", hanzi: "你平时喜欢做什么？", pinyin: "Nǐ píngshí xǐhuan zuò shénme?", english: "What do you usually like to do?" },
      { speaker: "you", hanzi: "我喜欢爬山，听音乐。", pinyin: "Wǒ xǐhuan páshān, tīng yīnyuè.", english: "I like hiking and listening to music." },
      { speaker: "npc", hanzi: "你听什么样的音乐？", pinyin: "Nǐ tīng shénme yàng de yīnyuè?", english: "What kind of music?" },
      { speaker: "you", hanzi: "什么都听，主要是摇滚。", pinyin: "Shénme dōu tīng, zhǔyào shì yáogǔn.", english: "A bit of everything, mostly rock." },
      { speaker: "npc", hanzi: "我也很喜欢摇滚！", pinyin: "Wǒ yě hěn xǐhuan yáogǔn!", english: "I love rock too!" },
      { speaker: "you", hanzi: "下次一起去看演唱会？", pinyin: "Xià cì yìqǐ qù kàn yǎnchànghuì?", english: "Want to catch a concert next time?" },
    ],
  },
  {
    id: "team-meeting",
    title: "Small team meeting",
    emoji: "🗂️",
    hskLevel: 4,
    minutes: 5,
    blurb: "Update the team on your project.",
    setting: "Weekly Monday morning standup.",
    turns: [
      { speaker: "npc", hanzi: "上周的进度怎么样？", pinyin: "Shàng zhōu de jìndù zěnmeyàng?", english: "How did last week go?" },
      { speaker: "you", hanzi: "完成了百分之七十。", pinyin: "Wánchéng le bǎi fēn zhī qīshí.", english: "We finished about seventy percent." },
      { speaker: "npc", hanzi: "遇到什么问题了？", pinyin: "Yùdào shénme wèntí le?", english: "Any problems?" },
      { speaker: "you", hanzi: "数据库有点慢。", pinyin: "Shùjùkù yǒudiǎn màn.", english: "The database is a bit slow." },
      { speaker: "npc", hanzi: "需要更多时间吗？", pinyin: "Xūyào gèng duō shíjiān ma?", english: "Do you need more time?" },
      { speaker: "you", hanzi: "可能需要两天。", pinyin: "Kěnéng xūyào liǎng tiān.", english: "Maybe two more days." },
      { speaker: "npc", hanzi: "好，我帮你协调一下。", pinyin: "Hǎo, wǒ bāng nǐ xiétiáo yíxià.", english: "Okay, I'll coordinate for you." },
    ],
  },
  {
    id: "trip-planning",
    title: "Plan a trip",
    emoji: "🗺️",
    hskLevel: 4,
    minutes: 4,
    blurb: "Plan a long weekend in Yunnan.",
    setting: "Two friends mapping out a Friday-to-Sunday trip.",
    turns: [
      { speaker: "you", hanzi: "我们五一去云南怎么样？", pinyin: "Wǒmen wǔ-yī qù Yúnnán zěnmeyàng?", english: "What about Yunnan for the May holiday?" },
      { speaker: "npc", hanzi: "好啊，去几天？", pinyin: "Hǎo a, qù jǐ tiān?", english: "Sounds good, how long?" },
      { speaker: "you", hanzi: "三天两夜。", pinyin: "Sān tiān liǎng yè.", english: "Three days, two nights." },
      { speaker: "npc", hanzi: "机票贵不贵？", pinyin: "Jīpiào guì bù guì?", english: "Are the flights expensive?" },
      { speaker: "you", hanzi: "现在订还行。", pinyin: "Xiànzài dìng hái xíng.", english: "Booking now is okay." },
      { speaker: "npc", hanzi: "酒店我来订。", pinyin: "Jiǔdiàn wǒ lái dìng.", english: "I'll book the hotel." },
    ],
  },
  {
    id: "argue-bill",
    title: "Dispute a bill",
    emoji: "🧾",
    hskLevel: 4,
    minutes: 4,
    blurb: "Question a charge on your bill.",
    setting: "Restaurant cashier — the total seems off.",
    turns: [
      { speaker: "you", hanzi: "我觉得账单不对。", pinyin: "Wǒ juéde zhàngdān bú duì.", english: "I think the bill is wrong." },
      { speaker: "npc", hanzi: "哪里有问题？", pinyin: "Nǎli yǒu wèntí?", english: "What's the issue?" },
      { speaker: "you", hanzi: "我没点这个汤。", pinyin: "Wǒ méi diǎn zhège tāng.", english: "I didn't order this soup." },
      { speaker: "npc", hanzi: "我再看一下。", pinyin: "Wǒ zài kàn yíxià.", english: "Let me check again." },
      { speaker: "you", hanzi: "请重新算一下。", pinyin: "Qǐng chóngxīn suàn yíxià.", english: "Please recalculate." },
      { speaker: "npc", hanzi: "对不起，是我们弄错了。", pinyin: "Duìbuqǐ, shì wǒmen nòng cuò le.", english: "Sorry, that was our mistake." },
    ],
  },
  {
    id: "discuss-news",
    title: "Talk about the news",
    emoji: "📰",
    hskLevel: 4,
    minutes: 4,
    blurb: "Trade thoughts on a current event.",
    setting: "Two friends over breakfast.",
    turns: [
      { speaker: "npc", hanzi: "你看了昨天的新闻吗？", pinyin: "Nǐ kàn le zuótiān de xīnwén ma?", english: "Did you see yesterday's news?" },
      { speaker: "you", hanzi: "看了一点，怎么了？", pinyin: "Kàn le yìdiǎn, zěnme le?", english: "A little, what's up?" },
      { speaker: "npc", hanzi: "那个公司又出问题了。", pinyin: "Nà ge gōngsī yòu chū wèntí le.", english: "That company is in trouble again." },
      { speaker: "you", hanzi: "真的吗？我不太了解。", pinyin: "Zhēn de ma? Wǒ bù tài liǎojiě.", english: "Really? I don't follow it closely." },
      { speaker: "npc", hanzi: "影响很多人。", pinyin: "Yǐngxiǎng hěn duō rén.", english: "It affects a lot of people." },
      { speaker: "you", hanzi: "希望能解决。", pinyin: "Xīwàng néng jiějué.", english: "Hopefully it'll be resolved." },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // HSK 5 — work, finance, culture, deeper conversation
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "quarterly-review",
    title: "Quarterly review",
    emoji: "📈",
    hskLevel: 5,
    minutes: 5,
    blurb: "Present quarterly results to a manager.",
    setting: "End-of-quarter one-on-one with your boss.",
    turns: [
      { speaker: "npc", hanzi: "这个季度的表现怎么样？", pinyin: "Zhège jìdù de biǎoxiàn zěnmeyàng?", english: "How was this quarter's performance?" },
      { speaker: "you", hanzi: "总体来说，达到了目标。", pinyin: "Zǒngtǐ lái shuō, dádào le mùbiāo.", english: "Overall, we hit our targets." },
      { speaker: "npc", hanzi: "哪些方面做得最好？", pinyin: "Nǎxiē fāngmiàn zuò de zuì hǎo?", english: "Which areas went best?" },
      { speaker: "you", hanzi: "客户增长超过了百分之二十。", pinyin: "Kèhù zēngzhǎng chāoguò le bǎi fēn zhī èrshí.", english: "Customer growth exceeded twenty percent." },
      { speaker: "npc", hanzi: "下个季度的计划？", pinyin: "Xià ge jìdù de jìhuà?", english: "Plans for next quarter?" },
      { speaker: "you", hanzi: "我们打算扩大产品线。", pinyin: "Wǒmen dǎsuàn kuòdà chǎnpǐn xiàn.", english: "We plan to expand the product line." },
      { speaker: "npc", hanzi: "需要哪些资源？", pinyin: "Xūyào nǎxiē zīyuán?", english: "What resources do you need?" },
      { speaker: "you", hanzi: "希望能多招两个人。", pinyin: "Xīwàng néng duō zhāo liǎng ge rén.", english: "Hopefully two more hires." },
    ],
  },
  {
    id: "supplier-negotiation",
    title: "Supplier negotiation",
    emoji: "🤲",
    hskLevel: 5,
    minutes: 5,
    blurb: "Negotiate a bulk purchase price.",
    setting: "Mid-sized factory floor with the sales rep.",
    turns: [
      { speaker: "npc", hanzi: "这是我们最优惠的价格了。", pinyin: "Zhè shì wǒmen zuì yōuhuì de jiàgé le.", english: "This is our best price." },
      { speaker: "you", hanzi: "还有讨论的空间吗？", pinyin: "Hái yǒu tǎolùn de kōngjiān ma?", english: "Is there room for discussion?" },
      { speaker: "npc", hanzi: "您打算订多少？", pinyin: "Nín dǎsuàn dìng duōshǎo?", english: "How much do you plan to order?" },
      { speaker: "you", hanzi: "如果一万件，能再降百分之五吗？", pinyin: "Rúguǒ yí wàn jiàn, néng zài jiàng bǎi fēn zhī wǔ ma?", english: "For 10,000 units, could you drop another 5%?" },
      { speaker: "npc", hanzi: "我得请示一下经理。", pinyin: "Wǒ děi qǐngshì yíxià jīnglǐ.", english: "I'll need to check with my manager." },
      { speaker: "you", hanzi: "希望能达成合作。", pinyin: "Xīwàng néng dáchéng hézuò.", english: "I hope we can do business." },
    ],
  },
  {
    id: "culture-discussion",
    title: "Culture differences",
    emoji: "🌏",
    hskLevel: 5,
    minutes: 4,
    blurb: "Discuss cultural differences with a friend.",
    setting: "Tea with a Chinese colleague who's curious about your background.",
    turns: [
      { speaker: "npc", hanzi: "你觉得中国和你的国家有什么不同？", pinyin: "Nǐ juéde Zhōngguó hé nǐ de guójiā yǒu shénme bùtóng?", english: "What differences do you see?" },
      { speaker: "you", hanzi: "饮食习惯差别很大。", pinyin: "Yǐnshí xíguàn chābié hěn dà.", english: "The food habits are quite different." },
      { speaker: "npc", hanzi: "比如说？", pinyin: "Bǐrú shuō?", english: "Such as?" },
      { speaker: "you", hanzi: "比如吃饭的时间和分量。", pinyin: "Bǐrú chīfàn de shíjiān hé fēnliàng.", english: "Like meal times and portions." },
      { speaker: "npc", hanzi: "你最喜欢中国哪一点？", pinyin: "Nǐ zuì xǐhuan Zhōngguó nǎ yì diǎn?", english: "What do you like most about China?" },
      { speaker: "you", hanzi: "人们对客人特别热情。", pinyin: "Rénmen duì kèrén tèbié rèqíng.", english: "People are very warm to guests." },
    ],
  },
  {
    id: "investment-talk",
    title: "Investment talk",
    emoji: "📊",
    hskLevel: 5,
    minutes: 4,
    blurb: "Compare investment ideas with a friend.",
    setting: "Two friends, one of whom just sold a stock.",
    turns: [
      { speaker: "npc", hanzi: "我刚把那只股票卖了。", pinyin: "Wǒ gāng bǎ nà zhī gǔpiào mài le.", english: "I just sold that stock." },
      { speaker: "you", hanzi: "为什么这个时候卖？", pinyin: "Wèishénme zhège shíhòu mài?", english: "Why now?" },
      { speaker: "npc", hanzi: "市场不太稳定。", pinyin: "Shìchǎng bú tài wěndìng.", english: "The market's unstable." },
      { speaker: "you", hanzi: "你现在打算放在哪里？", pinyin: "Nǐ xiànzài dǎsuàn fàng zài nǎli?", english: "Where will you put it now?" },
      { speaker: "npc", hanzi: "可能买基金，更稳。", pinyin: "Kěnéng mǎi jījīn, gèng wěn.", english: "Maybe a fund — steadier." },
      { speaker: "you", hanzi: "理财确实需要耐心。", pinyin: "Lǐcái quèshí xūyào nàixīn.", english: "Investing really needs patience." },
    ],
  },
  {
    id: "doctor-followup",
    title: "Doctor follow-up",
    emoji: "🩺",
    hskLevel: 5,
    minutes: 4,
    blurb: "Discuss test results with a specialist.",
    setting: "Specialist's office, week after the lab work.",
    turns: [
      { speaker: "npc", hanzi: "您的检查结果出来了。", pinyin: "Nín de jiǎnchá jiéguǒ chūlái le.", english: "Your test results are in." },
      { speaker: "you", hanzi: "情况怎么样？", pinyin: "Qíngkuàng zěnmeyàng?", english: "How does it look?" },
      { speaker: "npc", hanzi: "总体不错，但血压有点高。", pinyin: "Zǒngtǐ bú cuò, dàn xuèyā yǒudiǎn gāo.", english: "Overall fine, but blood pressure is a bit high." },
      { speaker: "you", hanzi: "需要吃药吗？", pinyin: "Xūyào chī yào ma?", english: "Do I need medication?" },
      { speaker: "npc", hanzi: "先调整生活习惯。", pinyin: "Xiān tiáozhěng shēnghuó xíguàn.", english: "First, adjust your lifestyle." },
      { speaker: "you", hanzi: "那我多运动，少吃盐。", pinyin: "Nà wǒ duō yùndòng, shǎo chī yán.", english: "I'll exercise more and eat less salt." },
    ],
  },
  {
    id: "feedback-on-essay",
    title: "Essay feedback",
    emoji: "✍️",
    hskLevel: 5,
    minutes: 4,
    blurb: "Get teacher feedback on your writing.",
    setting: "Teacher's office hour after class.",
    turns: [
      { speaker: "npc", hanzi: "你的文章写得不错。", pinyin: "Nǐ de wénzhāng xiě de bú cuò.", english: "Your essay is well done." },
      { speaker: "you", hanzi: "谢谢老师。哪里可以改进？", pinyin: "Xièxie lǎoshī. Nǎli kěyǐ gǎijìn?", english: "Thank you. Where could I improve?" },
      { speaker: "npc", hanzi: "结构清楚，但有些地方表达太长。", pinyin: "Jiégòu qīngchu, dàn yǒuxiē dìfāng biǎodá tài cháng.", english: "Structure is clear but some passages are too wordy." },
      { speaker: "you", hanzi: "我会注意。", pinyin: "Wǒ huì zhùyì.", english: "I'll watch for that." },
      { speaker: "npc", hanzi: "另外，可以多举一些例子。", pinyin: "Lìngwài, kěyǐ duō jǔ yìxiē lìzi.", english: "Also, give more examples." },
      { speaker: "you", hanzi: "明白了，下次我修改。", pinyin: "Míngbai le, xià cì wǒ xiūgǎi.", english: "Got it, I'll revise it next time." },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // HSK 6 — abstract, professional, opinion-driven
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "academic-presentation",
    title: "Academic presentation",
    emoji: "🎓",
    hskLevel: 6,
    minutes: 6,
    blurb: "Present a research finding.",
    setting: "Department seminar, audience of professors.",
    turns: [
      { speaker: "npc", hanzi: "请简要说明你的研究方法。", pinyin: "Qǐng jiǎnyào shuōmíng nǐ de yánjiū fāngfǎ.", english: "Please briefly describe your methodology." },
      { speaker: "you", hanzi: "我们采用了定量与定性相结合的方法。", pinyin: "Wǒmen cǎiyòng le dìngliàng yǔ dìngxìng xiāng jiéhé de fāngfǎ.", english: "We adopted a mixed quantitative-qualitative approach." },
      { speaker: "npc", hanzi: "样本量是多少？", pinyin: "Yàngběn liàng shì duōshǎo?", english: "What was the sample size?" },
      { speaker: "you", hanzi: "共采集了一千二百份有效问卷。", pinyin: "Gòng cǎijí le yī qiān èr bǎi fèn yǒuxiào wènjuàn.", english: "We collected 1,200 valid responses." },
      { speaker: "npc", hanzi: "结果是否具有统计意义？", pinyin: "Jiéguǒ shìfǒu jùyǒu tǒngjì yìyì?", english: "Are the results statistically significant?" },
      { speaker: "you", hanzi: "在百分之九十五的置信水平下显著。", pinyin: "Zài bǎi fēn zhī jiǔshíwǔ de zhìxìn shuǐpíng xià xiǎnzhù.", english: "Significant at the 95% confidence level." },
      { speaker: "npc", hanzi: "你认为局限性在哪里？", pinyin: "Nǐ rènwéi júxiànxìng zài nǎli?", english: "Where do you see limitations?" },
      { speaker: "you", hanzi: "样本主要来自一线城市，普适性有限。", pinyin: "Yàngběn zhǔyào láizì yīxiàn chéngshì, pǔshìxìng yǒuxiàn.", english: "The sample is mostly tier-1 cities, so generalizability is limited." },
    ],
  },
  {
    id: "ethics-debate",
    title: "Ethics debate",
    emoji: "⚖️",
    hskLevel: 6,
    minutes: 5,
    blurb: "Argue an ethical dilemma.",
    setting: "Coffee with a philosophy major friend.",
    turns: [
      { speaker: "npc", hanzi: "你怎么看人工智能取代工作？", pinyin: "Nǐ zěnme kàn réngōng zhìnéng qǔdài gōngzuò?", english: "What do you think about AI replacing jobs?" },
      { speaker: "you", hanzi: "这个问题不能简单地下结论。", pinyin: "Zhège wèntí bùnéng jiǎndān de xià jiélùn.", english: "It's not a question with a simple answer." },
      { speaker: "npc", hanzi: "为什么这么说？", pinyin: "Wèishénme zhème shuō?", english: "Why do you say that?" },
      { speaker: "you", hanzi: "技术进步既带来效率，也带来失业风险。", pinyin: "Jìshù jìnbù jì dàilái xiàolǜ, yě dàilái shīyè fēngxiǎn.", english: "Tech progress brings efficiency but also unemployment risk." },
      { speaker: "npc", hanzi: "那应该限制发展吗？", pinyin: "Nà yīnggāi xiànzhì fāzhǎn ma?", english: "Should we limit its development?" },
      { speaker: "you", hanzi: "限制不可行，应该完善社会保障。", pinyin: "Xiànzhì bù kěxíng, yīnggāi wánshàn shèhuì bǎozhàng.", english: "Limits aren't feasible — strengthen social safety nets instead." },
      { speaker: "npc", hanzi: "你说的有道理。", pinyin: "Nǐ shuō de yǒu dàolǐ.", english: "That makes sense." },
    ],
  },
  {
    id: "literary-discussion",
    title: "Literary discussion",
    emoji: "📚",
    hskLevel: 6,
    minutes: 5,
    blurb: "Discuss a novel with a book club.",
    setting: "Monthly book club meeting at a member's home.",
    turns: [
      { speaker: "npc", hanzi: "你怎么理解小说的结尾？", pinyin: "Nǐ zěnme lǐjiě xiǎoshuō de jiéwěi?", english: "How do you read the ending?" },
      { speaker: "you", hanzi: "我觉得作者故意留下空间。", pinyin: "Wǒ juéde zuòzhě gùyì liú xià kōngjiān.", english: "I think the author intentionally leaves it open." },
      { speaker: "npc", hanzi: "为什么留下空间？", pinyin: "Wèishénme liú xià kōngjiān?", english: "Why leave it open?" },
      { speaker: "you", hanzi: "让读者反思自己的处境。", pinyin: "Ràng dúzhě fǎnsī zìjǐ de chǔjìng.", english: "To make the reader reflect on their own situation." },
      { speaker: "npc", hanzi: "主人公是不是太消极？", pinyin: "Zhǔréngōng shì bú shì tài xiāojí?", english: "Isn't the protagonist too passive?" },
      { speaker: "you", hanzi: "他的消极反映了时代的无力感。", pinyin: "Tā de xiāojí fǎnyìng le shídài de wúlì gǎn.", english: "His passivity reflects the era's helplessness." },
    ],
  },
  {
    id: "policy-discussion",
    title: "Policy discussion",
    emoji: "🏛️",
    hskLevel: 6,
    minutes: 5,
    blurb: "Discuss a new public policy.",
    setting: "Friends debating a new urban policy over dinner.",
    turns: [
      { speaker: "npc", hanzi: "你支持新的限行政策吗？", pinyin: "Nǐ zhīchí xīn de xiànxíng zhèngcè ma?", english: "Do you support the new traffic policy?" },
      { speaker: "you", hanzi: "出发点是好的，但执行有问题。", pinyin: "Chūfādiǎn shì hǎo de, dàn zhíxíng yǒu wèntí.", english: "The intent is good but execution is flawed." },
      { speaker: "npc", hanzi: "具体哪里有问题？", pinyin: "Jùtǐ nǎli yǒu wèntí?", english: "Specifically?" },
      { speaker: "you", hanzi: "公共交通跟不上，老百姓很麻烦。", pinyin: "Gōnggòng jiāotōng gēn bú shàng, lǎobǎixìng hěn máfan.", english: "Public transit can't keep up — people suffer." },
      { speaker: "npc", hanzi: "那应该怎么改进？", pinyin: "Nà yīnggāi zěnme gǎijìn?", english: "How should it be improved?" },
      { speaker: "you", hanzi: "应该先扩展地铁线，再限行。", pinyin: "Yīnggāi xiān kuòzhǎn dìtiě xiàn, zài xiànxíng.", english: "Expand the metro first, then restrict driving." },
    ],
  },
  {
    id: "career-pivot",
    title: "Career pivot conversation",
    emoji: "🔁",
    hskLevel: 6,
    minutes: 5,
    blurb: "Tell a mentor you're switching fields.",
    setting: "Coffee with a long-time mentor.",
    turns: [
      { speaker: "you", hanzi: "我考虑转行了。", pinyin: "Wǒ kǎolǜ zhuǎnháng le.", english: "I'm thinking of changing careers." },
      { speaker: "npc", hanzi: "你想清楚了吗？", pinyin: "Nǐ xiǎng qīngchu le ma?", english: "Have you really thought it through?" },
      { speaker: "you", hanzi: "想了很久，现在的工作让我没动力。", pinyin: "Xiǎng le hěn jiǔ, xiànzài de gōngzuò ràng wǒ méi dònglì.", english: "I've thought about it a long time — my current work doesn't motivate me." },
      { speaker: "npc", hanzi: "你的家人怎么看？", pinyin: "Nǐ de jiārén zěnme kàn?", english: "What does your family think?" },
      { speaker: "you", hanzi: "他们尊重我的选择。", pinyin: "Tāmen zūnzhòng wǒ de xuǎnzé.", english: "They respect my choice." },
      { speaker: "npc", hanzi: "新行业有什么挑战？", pinyin: "Xīn hángyè yǒu shénme tiǎozhàn?", english: "What challenges in the new field?" },
      { speaker: "you", hanzi: "需要重新积累经验。", pinyin: "Xūyào chóngxīn jīlěi jīngyàn.", english: "I'll have to build experience from scratch." },
    ],
  },
];

export function findScenario(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}

/** Distinct HSK levels covered, sorted ascending. */
export function scenarioLevels(): number[] {
  return Array.from(new Set(SCENARIOS.map((s) => s.hskLevel))).sort((a, b) => a - b);
}

export function scenariosByLevel(level: number): Scenario[] {
  return SCENARIOS.filter((s) => s.hskLevel === level);
}
