/**
 * Pattern Sprints — drill one grammar construction with varied vocabulary,
 * speeding up over many short repetitions until production becomes reflexive.
 *
 * Data format on disk (data/patterns/hsk{1..6}_patterns.json):
 *   {
 *     level: "HSK1+HSK2+...",
 *     constructions: [
 *       { id, name, ru_name, pattern, patterns: [{ ru, zh, py }, ...] },
 *       ...
 *     ]
 *   }
 *
 * Six files cover cumulative vocabulary scopes (HSK1, HSK1–2, …, HSK1–6).
 * The same 30 constructions appear in every file — what changes is the example
 * sentences, which only use lexis up to the chosen level. Constructions
 * themselves are HSK 1 grammar for now.
 */

export type LexicalLevel = 1 | 2 | 3 | 4 | 5 | 6;
/**
 * Which HSK level's grammar constructions to drill. The lexical level is a
 * separate dimension — every grammar level has cumulative vocab scopes.
 * HSK 1 grammar covers scopes V1..V6, HSK 2 covers V12..V123456, HSK 3
 * covers V123..V123456.
 */
export type GrammarLevel = 1 | 2 | 3;

/**
 * The Russian field is the original authored translation; the rest are
 * generated by `scripts/translate-patterns.mjs` from the Chinese sentence and
 * may not yet exist on every phrase. Always treat the non-`ru` fields as
 * optional and fall back through `getPhraseTranslation()` to keep the trainer
 * resilient while the cache is being filled.
 */
export type PatternPhrase = {
  ru: string;
  zh: string;
  py: string;
  en?: string;
  de?: string;
  es?: string;
  pt?: string;
  pl?: string;
  uk?: string;
};

/** Two-letter codes the trainer can render. Order = fallback order. */
export const SUPPORTED_PHRASE_LANGS = [
  "ru",
  "en",
  "es",
  "pt",
  "de",
  "pl",
  "uk",
] as const;
export type PhraseLang = (typeof SUPPORTED_PHRASE_LANGS)[number];

/**
 * Pick the phrase text for the given UI language with a sensible fallback
 * chain: requested → en → ru (which is always present in the source data).
 */
export function getPhraseTranslation(
  phrase: PatternPhrase,
  lang: string,
): { text: string; lang: PhraseLang } {
  const code = (SUPPORTED_PHRASE_LANGS as readonly string[]).includes(lang)
    ? (lang as PhraseLang)
    : "en";
  const direct = phrase[code];
  if (direct) return { text: direct, lang: code };
  if (phrase.en) return { text: phrase.en, lang: "en" };
  return { text: phrase.ru, lang: "ru" };
}

/**
 * Localized construction descriptions. `ru` is the curated source; the rest
 * are generated by `scripts/translate-construction-names.mjs`. Optional so the
 * resolver stays resilient if a file predates the generator.
 */
export type ConstructionNameI18n = {
  ru: string;
  en?: string;
  de?: string;
  es?: string;
  pt?: string;
  pl?: string;
  uk?: string;
};

export type Construction = {
  id: number;
  name: string;
  ru_name: string;
  /** Per-language description; falls back to `ru_name` via `constructionName()`. */
  name_i18n?: ConstructionNameI18n;
  pattern: string;
  patterns: PatternPhrase[];
};

/**
 * Pick the construction's description for the given UI language. Fallback
 * chain: requested → en → ru_name (always present in the source data).
 */
export function constructionName(c: Construction, lang: string): string {
  const i18n = c.name_i18n;
  if (i18n) {
    const code = (SUPPORTED_PHRASE_LANGS as readonly string[]).includes(lang)
      ? (lang as PhraseLang)
      : "en";
    const direct = i18n[code as keyof ConstructionNameI18n];
    if (direct) return direct;
    if (i18n.en) return i18n.en;
  }
  return c.ru_name;
}

export type PatternsBundle = {
  level: string;
  title: string;
  method: string;
  vocabulary_constraint: string;
  how_to_use: string[];
  constructions: Construction[];
};

// Static `require` map indexed by (grammarLevel, lexicalLevel). Metro needs
// literal paths at bundle time; functions defer the JSON parse until first
// use so the trainer's startup cost stays small.
type LoaderMap = Partial<Record<LexicalLevel, () => PatternsBundle>>;

const LOADERS: Record<GrammarLevel, LoaderMap> = {
  1: {
    1: () => require("../../../data/patterns/hsk1_patterns.json") as PatternsBundle,
    2: () => require("../../../data/patterns/hsk1_2_patterns.json") as PatternsBundle,
    3: () => require("../../../data/patterns/hsk1_2_3_patterns.json") as PatternsBundle,
    4: () => require("../../../data/patterns/hsk1_2_3_4_patterns.json") as PatternsBundle,
    5: () => require("../../../data/patterns/hsk1_2_3_4_5_patterns.json") as PatternsBundle,
    6: () => require("../../../data/patterns/hsk1_2_3_4_5_6_patterns.json") as PatternsBundle,
  },
  2: {
    // HSK 2 grammar — cumulative vocab scopes (V12 → V123456) generated via
    // scripts/generate-hsk2-patterns.mjs. Each scope inherits its smaller
    // sibling's phrases plus new ones using the freshly available HSK level.
    2: () => require("../../../data/patterns/hsk2_patterns.json") as PatternsBundle,
    3: () => require("../../../data/patterns/hsk2_3_patterns.json") as PatternsBundle,
    4: () => require("../../../data/patterns/hsk2_3_4_patterns.json") as PatternsBundle,
    5: () => require("../../../data/patterns/hsk2_3_4_5_patterns.json") as PatternsBundle,
    6: () => require("../../../data/patterns/hsk2_3_4_5_6_patterns.json") as PatternsBundle,
  },
  3: {
    // HSK 3 grammar — generated via scripts/generate-hsk3-patterns.mjs.
    // Smallest scope is V123 (the learner already knows HSK 1+2 vocab),
    // then V1234, V12345, V123456.
    3: () => require("../../../data/patterns/hsk3_patterns.json") as PatternsBundle,
    4: () => require("../../../data/patterns/hsk3_4_patterns.json") as PatternsBundle,
    5: () => require("../../../data/patterns/hsk3_4_5_patterns.json") as PatternsBundle,
    6: () => require("../../../data/patterns/hsk3_4_5_6_patterns.json") as PatternsBundle,
  },
};

const cache = new Map<string, PatternsBundle>();

function cacheKey(g: GrammarLevel, l: LexicalLevel): string {
  return `${g}:${l}`;
}

/**
 * Available lexical scopes for a given grammar level. The trainer uses this
 * to populate the level chip row.
 *
 * Files marked as `level === "placeholder"` (created up-front so Metro can
 * resolve every require() but not yet filled by the generator script) are
 * filtered out so users can't pick an empty scope.
 */
export function availableLexicalLevels(grammar: GrammarLevel): LexicalLevel[] {
  const result: LexicalLevel[] = [];
  for (const key of Object.keys(LOADERS[grammar])) {
    const lvl = Number(key) as LexicalLevel;
    try {
      const bundle = loadPatternsBundle(grammar, lvl);
      if (bundle.level !== "placeholder" && bundle.constructions.length > 0) {
        result.push(lvl);
      }
    } catch {
      // skip unloadable scope
    }
  }
  return result.sort((a, b) => a - b);
}

/** First (smallest) lexical scope offered for a grammar level. */
export function defaultLexicalLevelFor(grammar: GrammarLevel): LexicalLevel {
  const arr = availableLexicalLevels(grammar);
  return arr[0] ?? 1;
}

export function loadPatternsBundle(
  grammar: GrammarLevel,
  lexical: LexicalLevel,
): PatternsBundle {
  const k = cacheKey(grammar, lexical);
  const cached = cache.get(k);
  if (cached) return cached;
  const loader = LOADERS[grammar][lexical];
  if (!loader) {
    // Fall back to the smallest available scope so the screen stays usable.
    const fallbackLexical = defaultLexicalLevelFor(grammar);
    const fb = LOADERS[grammar][fallbackLexical]?.();
    if (!fb) throw new Error(`No bundle for grammar=${grammar}`);
    cache.set(k, fb);
    return fb;
  }
  const bundle = loader();
  cache.set(k, bundle);
  return bundle;
}

export function listConstructions(
  grammar: GrammarLevel,
  lexical: LexicalLevel,
): Construction[] {
  return loadPatternsBundle(grammar, lexical).constructions;
}

export function getConstruction(
  grammar: GrammarLevel,
  lexical: LexicalLevel,
  id: number,
): Construction | null {
  const found = loadPatternsBundle(grammar, lexical).constructions.find(
    (c) => c.id === id,
  );
  return found ?? null;
}

export const DEFAULT_GRAMMAR_LEVEL: GrammarLevel = 1;
export const DEFAULT_LEXICAL_LEVEL: LexicalLevel = 1;
export const ALL_GRAMMAR_LEVELS: GrammarLevel[] = [1, 2, 3];
export const ALL_LEXICAL_LEVELS: LexicalLevel[] = [1, 2, 3, 4, 5, 6];
