INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('然', ARRAY['rán'], ARRAY['ran'], 2, 201),
('但', ARRAY['dàn'], ARRAY['but'], 2, 202),
('从', ARRAY['cóng'], ARRAY['from'], 2, 203),
('比', ARRAY['bǐ'], ARRAY['compare'], 2, 204),
('往', ARRAY['wǎng'], ARRAY['past'], 2, 205),
('离', ARRAY['lí'], ARRAY['leave'], 2, 206),
('得', ARRAY['dé','děi','de'], ARRAY['have to'], 2, 207),
('着', ARRAY['zhe','zhuó','zháo','zhāo'], ARRAY['with'], 2, 208),
('过', ARRAY['guò','guo','guō'], ARRAY['pass'], 2, 209),
('吧', ARRAY['ba','bā'], ARRAY['bar'], 2, 210),
('场', ARRAY['chǎng','cháng'], ARRAY['field'], 2, 211),
('教', ARRAY['jiào','jiāo'], ARRAY['teach'], 2, 212),
('室', ARRAY['shì'], ARRAY['room'], 2, 213),
('房', ARRAY['fáng'], ARRAY['house'], 2, 214),
('间', ARRAY['jiān','jiàn'], ARRAY['between'], 2, 215),
('路', ARRAY['lù'], ARRAY['road'], 2, 216),
('左', ARRAY['zuǒ'], ARRAY['left'], 2, 217),
('边', ARRAY['biān','bian'], ARRAY['side'], 2, 218),
('右', ARRAY['yòu'], ARRAY['right'], 2, 219),
('外', ARRAY['wài'], ARRAY['outside'], 2, 220),
('旁', ARRAY['páng','bàng'], ARRAY['beside'], 2, 221),
('早', ARRAY['zǎo'], ARRAY['morning'], 2, 222),
('晚', ARRAY['wǎn'], ARRAY['night'], 2, 223),
('日', ARRAY['rì'], ARRAY['day'], 2, 224),
('哥', ARRAY['gē'], ARRAY['elder brother'], 2, 225),
('弟', ARRAY['dì','tì','tuí'], ARRAY['younger brother'], 2, 226),
('妹', ARRAY['mèi'], ARRAY['sister'], 2, 227),
('丈', ARRAY['zhàng'], ARRAY['ten feet'], 2, 228),
('夫', ARRAY['fū','fú'], ARRAY['husband'], 2, 229),
('妻', ARRAY['qī','qì'], ARRAY['wife'], 2, 230),
('孩', ARRAY['hái'], ARRAY['child'], 2, 231),
('男', ARRAY['nán'], ARRAY['male'], 2, 232),
('务', ARRAY['wù'], ARRAY['service'], 2, 233),
('员', ARRAY['yuán','yún','yùn'], ARRAY['member'], 2, 234),
('鱼', ARRAY['yú'], ARRAY['fish'], 2, 235),
('羊', ARRAY['yáng','xiáng'], ARRAY['sheep'], 2, 236),
('肉', ARRAY['ròu'], ARRAY['meat'], 2, 237),
('牛', ARRAY['niú'], ARRAY['ox'], 2, 238),
('奶', ARRAY['nǎi'], ARRAY['milk'], 2, 239),
('鸡', ARRAY['jī'], ARRAY['chicken'], 2, 240),
('蛋', ARRAY['dàn'], ARRAY['egg'], 2, 241),
('瓜', ARRAY['guā'], ARRAY['melon'], 2, 242),
('咖', ARRAY['kā','gā'], ARRAY['coffee'], 2, 243),
('啡', ARRAY['fēi'], ARRAY['coffee'], 2, 244),
('雪', ARRAY['xuě'], ARRAY['snow'], 2, 245),
('药', ARRAY['yào'], ARRAY['medicine'], 2, 246),
('手', ARRAY['shǒu'], ARRAY['hand'], 2, 247),
('表', ARRAY['biǎo'], ARRAY['surface'], 2, 248),
('眼', ARRAY['yǎn'], ARRAY['eye'], 2, 249),
('睛', ARRAY['jīng'], ARRAY['eye'], 2, 250)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);