INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('态', ARRAY['tài'], ARRAY['state'], 4, 951),
('谈', ARRAY['tán'], ARRAY['talk'], 4, 952),
('弹', ARRAY['tán','dàn'], ARRAY['bomb'], 4, 953),
('钢', ARRAY['gāng','gàng'], ARRAY['steel'], 4, 954),
('琴', ARRAY['qín'], ARRAY['piano'], 4, 955),
('汤', ARRAY['tāng','shāng'], ARRAY['soup'], 4, 956),
('糖', ARRAY['táng'], ARRAY['sugar'], 4, 957),
('躺', ARRAY['tǎng'], ARRAY['lie'], 4, 958),
('趟', ARRAY['tàng','tāng'], ARRAY['trip'], 4, 959),
('讨', ARRAY['tǎo'], ARRAY['discuss'], 4, 960),
('论', ARRAY['lùn','lún'], ARRAY['argument'], 4, 961),
('厌', ARRAY['yàn'], ARRAY['disgusted'], 4, 962),
('供', ARRAY['gòng','gōng'], ARRAY['for'], 4, 963),
('醒', ARRAY['xǐng'], ARRAY['awake'], 4, 964),
('填', ARRAY['tián','zhèn'], ARRAY['fill'], 4, 965),
('停', ARRAY['tíng'], ARRAY['stop'], 4, 966),
('挺', ARRAY['tǐng'], ARRAY['quite'], 4, 967),
('推', ARRAY['tuī'], ARRAY['push'], 4, 968),
('脱', ARRAY['tuō'], ARRAY['take off'], 4, 969),
('袜', ARRAY['wà'], ARRAY['socks'], 4, 970),
('危', ARRAY['wēi'], ARRAY['danger'], 4, 971),
('险', ARRAY['xiǎn'], ARRAY['risk'], 4, 972),
('味', ARRAY['wèi'], ARRAY['taste'], 4, 973),
('卫', ARRAY['wèi'], ARRAY['guard'], 4, 974),
('温', ARRAY['wēn'], ARRAY['temperature'], 4, 975),
('章', ARRAY['zhāng'], ARRAY['chapter'], 4, 976),
('污', ARRAY['wū'], ARRAY['dirty'], 4, 977),
('染', ARRAY['rǎn'], ARRAY['dye'], 4, 978),
('无', ARRAY['wú','mó'], ARRAY['none'], 4, 979),
('柿', ARRAY['shì'], ARRAY['persimmon'], 4, 980),
('吸', ARRAY['xī'], ARRAY['suck'], 4, 981),
('引', ARRAY['yǐn'], ARRAY['lead'], 4, 982),
('咸', ARRAY['xián'], ARRAY['salty'], 4, 983),
('羡', ARRAY['xiàn'], ARRAY['envy'], 4, 984),
('慕', ARRAY['mù'], ARRAY['mu'], 4, 985),
('详', ARRAY['xiáng','yáng'], ARRAY['detailed'], 4, 986),
('细', ARRAY['xì'], ARRAY['thin'], 4, 987),
('橡', ARRAY['xiàng'], ARRAY['oak'], 4, 988),
('消', ARRAY['xiāo'], ARRAY['remove'], 4, 989),
('伙', ARRAY['huǒ'], ARRAY['partner'], 4, 990),
('效', ARRAY['xiào'], ARRAY['effect'], 4, 991),
('辛', ARRAY['xīn'], ARRAY['pungent'], 4, 992),
('封', ARRAY['fēng'], ARRAY['seal up'], 4, 993),
('奋', ARRAY['fèn'], ARRAY['work hard'], 4, 994),
('性', ARRAY['xìng'], ARRAY['sex'], 4, 995),
('幸', ARRAY['xìng'], ARRAY['fortunate'], 4, 996),
('福', ARRAY['fú'], ARRAY['blessing'], 4, 997),
('修', ARRAY['xiū'], ARRAY['build'], 4, 998),
('许', ARRAY['xǔ','hǔ'], ARRAY['may'], 4, 999),
('压', ARRAY['yā','yà'], ARRAY['press'], 4, 1000)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);