INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('植', ARRAY['zhí'], ARRAY['plant'], 4, 1051),
('职', ARRAY['zhí'], ARRAY['position'], 4, 1052),
('指', ARRAY['zhǐ'], ARRAY['refer to'], 4, 1053),
('质', ARRAY['zhì'], ARRAY['quality'], 4, 1054),
('围', ARRAY['wéi'], ARRAY['surround'], 4, 1055),
('祝', ARRAY['zhù'], ARRAY['wish'], 4, 1056),
('贺', ARRAY['hè'], ARRAY['congratulations'], 4, 1057),
('著', ARRAY['zhù','zhuó','zhe'], ARRAY['write'], 4, 1058),
('专', ARRAY['zhuān'], ARRAY['specialize'], 4, 1059),
('转', ARRAY['zhuǎn','zhuàn','zhuǎi'], ARRAY['change'], 4, 1060),
('赚', ARRAY['zhuàn','zuàn'], ARRAY['earn'], 4, 1061),
('仔', ARRAY['zǎi','zǐ','zī'], ARRAY['young'], 4, 1062),
('尊', ARRAY['zūn'], ARRAY['respect'], 4, 1063),
('座', ARRAY['zuò'], ARRAY['seat'], 4, 1064),
('唉', ARRAY['ài','āi'], ARRAY['well'], 5, 1065),
('慰', ARRAY['wèi'], ARRAY['comfort'], 5, 1066),
('岸', ARRAY['àn'], ARRAY['shore'], 5, 1067),
('熬', ARRAY['áo','āo'], ARRAY['boil'], 5, 1068),
('夜', ARRAY['yè'], ARRAY['night'], 5, 1069),
('含', ARRAY['hán'], ARRAY['contains'], 5, 1070),
('宝', ARRAY['bǎo'], ARRAY['precious'], 5, 1071),
('悲', ARRAY['bēi'], ARRAY['sad'], 5, 1072),
('背', ARRAY['bèi','bēi'], ARRAY['back'], 5, 1073),
('领', ARRAY['lǐng'], ARRAY['collar'], 5, 1074),
('鞭', ARRAY['biān'], ARRAY['whip'], 5, 1075),
('炮', ARRAY['pào','páo','bāo'], ARRAY['gun'], 5, 1076),
('辩', ARRAY['biàn'], ARRAY['debate'], 5, 1077),
('达', ARRAY['dá'], ARRAY['reach'], 5, 1078),
('凌', ARRAY['líng'], ARRAY['ling'], 5, 1079),
('玻', ARRAY['bō'], ARRAY['glass'], 5, 1080),
('璃', ARRAY['lí'], ARRAY['glass'], 5, 1081),
('补', ARRAY['bǔ'], ARRAY['repair'], 5, 1082),
('充', ARRAY['chōng'], ARRAY['charge'], 5, 1083),
('财', ARRAY['cái'], ARRAY['fiscal'], 5, 1084),
('产', ARRAY['chǎn'], ARRAY['produce'], 5, 1085),
('踩', ARRAY['cǎi'], ARRAY['step on'], 5, 1086),
('采', ARRAY['cǎi','cài'], ARRAY['pick'], 5, 1087),
('操', ARRAY['cāo'], ARRAY['hold'], 5, 1088),
('插', ARRAY['chā'], ARRAY['insert'], 5, 1089),
('叉', ARRAY['chā','chà','chǎ','chá'], ARRAY['fork'], 5, 1090),
('拆', ARRAY['chāi','cā'], ARRAY['dismantle'], 5, 1091),
('潮', ARRAY['cháo'], ARRAY['tide'], 5, 1092),
('湿', ARRAY['shī'], ARRAY['wet'], 5, 1093),
('吵', ARRAY['chǎo','chāo'], ARRAY['quarrel'], 5, 1094),
('库', ARRAY['kù'], ARRAY['library'], 5, 1095),
('彻', ARRAY['chè'], ARRAY['thorough'], 5, 1096),
('趁', ARRAY['chèn'], ARRAY['take advantage of'], 5, 1097),
('称', ARRAY['chēng','chèn','chèng'], ARRAY['say'], 5, 1098),
('赞', ARRAY['zàn'], ARRAY['praise'], 5, 1099),
('承', ARRAY['chéng'], ARRAY['inherit'], 5, 1100)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);