INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('绸', ARRAY['chóu'], ARRAY['silk'], 5, 1301),
('似', ARRAY['sì','shì'], ARRAY['like'], 5, 1302),
('碎', ARRAY['suì'], ARRAY['broken'], 5, 1303),
('损', ARRAY['sǔn'], ARRAY['damage'], 5, 1304),
('锁', ARRAY['suǒ'], ARRAY['lock'], 5, 1305),
('阶', ARRAY['jiē'], ARRAY['level'], 5, 1306),
('拳', ARRAY['quán'], ARRAY['fist'], 5, 1307),
('逃', ARRAY['táo'], ARRAY['escape'], 5, 1308),
('淘', ARRAY['táo'], ARRAY['tao'], 5, 1309),
('套', ARRAY['tào'], ARRAY['set'], 5, 1310),
('倡', ARRAY['chàng','chāng'], ARRAY['advocate'], 5, 1311),
('贴', ARRAY['tiē'], ARRAY['stick'], 5, 1312),
('痛', ARRAY['tòng'], ARRAY['pain'], 5, 1313),
('偷', ARRAY['tōu'], ARRAY['steal'], 5, 1314),
('投', ARRAY['tóu'], ARRAY['cast'], 5, 1315),
('土', ARRAY['tǔ'], ARRAY['earth'], 5, 1316),
('豆', ARRAY['dòu'], ARRAY['bean'], 5, 1317),
('兔', ARRAY['tù'], ARRAY['rabbit'], 5, 1318),
('辞', ARRAY['cí'], ARRAY['ci'], 5, 1319),
('荐', ARRAY['jiàn'], ARRAY['recommend'], 5, 1320),
('退', ARRAY['tuì'], ARRAY['retreat'], 5, 1321),
('威', ARRAY['wēi'], ARRAY['power'], 5, 1322),
('胁', ARRAY['xié'], ARRAY['threaten'], 5, 1323),
('维', ARRAY['wéi'], ARRAY['dimension'], 5, 1324),
('尾', ARRAY['wěi','yǐ'], ARRAY['tail'], 5, 1325),
('巴', ARRAY['bā'], ARRAY['-bar'], 5, 1326),
('委', ARRAY['wěi','wēi'], ARRAY['committee'], 5, 1327),
('屈', ARRAY['qū'], ARRAY['qu'], 5, 1328),
('胃', ARRAY['wèi'], ARRAY['stomach'], 5, 1329),
('未', ARRAY['wèi'], ARRAY['not yet'], 5, 1330),
('柔', ARRAY['róu'], ARRAY['soft'], 5, 1331),
('稳', ARRAY['wěn'], ARRAY['stable'], 5, 1332),
('卧', ARRAY['wò'], ARRAY['lie down'], 5, 1333),
('勿', ARRAY['wù'], ARRAY['do not'], 5, 1334),
('吓', ARRAY['xià','hè'], ARRAY['scare'], 5, 1335),
('营', ARRAY['yíng'], ARRAY['camp'], 5, 1336),
('载', ARRAY['zǎi','zài'], ARRAY['load'], 5, 1337),
('县', ARRAY['xiàn','xuán'], ARRAY['county'], 5, 1338),
('肠', ARRAY['cháng'], ARRAY['intestinal'], 5, 1339),
('享', ARRAY['xiǎng'], ARRAY['enjoy'], 5, 1340),
('项', ARRAY['xiàng'], ARRAY['item'], 5, 1341),
('链', ARRAY['liàn'], ARRAY['chain'], 5, 1342),
('征', ARRAY['zhēng'], ARRAY['levy'], 5, 1343),
('孝', ARRAY['xiào'], ARRAY['filial piety'], 5, 1344),
('斜', ARRAY['xié'], ARRAY['incline'], 5, 1345),
('形', ARRAY['xíng'], ARRAY['shape'], 5, 1346),
('状', ARRAY['zhuàng'], ARRAY['shape'], 5, 1347),
('兄', ARRAY['xiōng'], ARRAY['brother'], 5, 1348),
('宣', ARRAY['xuān'], ARRAY['announce'], 5, 1349),
('询', ARRAY['xún'], ARRAY['inquire'], 5, 1350)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);