INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('押', ARRAY['yā'], ARRAY['pledge'], 5, 1351),
('齿', ARRAY['chǐ'], ARRAY['tooth'], 5, 1352),
('宴', ARRAY['yàn'], ARRAY['feast'], 5, 1353),
('痒', ARRAY['yǎng'], ARRAY['itch'], 5, 1354),
('腰', ARRAY['yāo'], ARRAY['waist'], 5, 1355),
('咬', ARRAY['yǎo'], ARRAY['bite'], 5, 1356),
('余', ARRAY['yú'], ARRAY['remain'], 5, 1357),
('依', ARRAY['yī'], ARRAY['according to'], 5, 1358),
('旦', ARRAY['dàn'], ARRAY['dawn'], 5, 1359),
('致', ARRAY['zhì'], ARRAY['to'], 5, 1360),
('移', ARRAY['yí'], ARRAY['shift'], 5, 1361),
('义', ARRAY['yì'], ARRAY['righteous'], 5, 1362),
('素', ARRAY['sù'], ARRAY['white'], 5, 1363),
('英', ARRAY['yīng'], ARRAY['britain'], 5, 1364),
('俊', ARRAY['jùn'], ARRAY['hansome'], 5, 1365),
('硬', ARRAY['yìng'], ARRAY['hard'], 5, 1366),
('拥', ARRAY['yōng'], ARRAY['possess'], 5, 1367),
('挤', ARRAY['jǐ'], ARRAY['squeeze'], 5, 1368),
('惠', ARRAY['huì'], ARRAY['benefit'], 5, 1369),
('悠', ARRAY['yōu'], ARRAY['you'], 5, 1370),
('炸', ARRAY['zhà','zhá'], ARRAY['fry'], 5, 1371),
('娱', ARRAY['yú'], ARRAY['entertainment'], 5, 1372),
('防', ARRAY['fáng'], ARRAY['defend'], 5, 1373),
('圆', ARRAY['yuán'], ARRAY['round'], 5, 1374),
('晕', ARRAY['yūn','yùn'], ARRAY['faint'], 5, 1375),
('灾', ARRAY['zāi'], ARRAY['disaster'], 5, 1376),
('糟', ARRAY['zāo'], ARRAY['bad'], 5, 1377),
('造', ARRAY['zào'], ARRAY['make'], 5, 1378),
('窄', ARRAY['zhǎi'], ARRAY['narrow'], 5, 1379),
('握', ARRAY['wò'], ARRAY['grip'], 5, 1380),
('珍', ARRAY['zhēn'], ARRAY['jane'], 5, 1381),
('阵', ARRAY['zhèn'], ARRAY['array'], 5, 1382),
('睁', ARRAY['zhēng'], ARRAY['open eyes'], 5, 1383),
('齐', ARRAY['qí','jì','zī','zhāi'], ARRAY['together'], 5, 1384),
('政', ARRAY['zhèng'], ARRAY['politics'], 5, 1385),
('府', ARRAY['fǔ'], ARRAY['mansion'], 5, 1386),
('智', ARRAY['zhì'], ARRAY['wisdom'], 5, 1387),
('慧', ARRAY['huì'], ARRAY['wisdom'], 5, 1388),
('秩', ARRAY['zhì'], ARRAY['rank'], 5, 1389),
('旬', ARRAY['xún'], ARRAY['ten days'], 5, 1390),
('逐', ARRAY['zhú'], ARRAY['chase'], 5, 1391),
('竹', ARRAY['zhú'], ARRAY['bamboo'], 5, 1392),
('抓', ARRAY['zhuā'], ARRAY['grasp'], 5, 1393),
('追', ARRAY['zhuī','duī'], ARRAY['chase'], 5, 1394),
('姿', ARRAY['zī'], ARRAY['posture'], 5, 1395),
('紫', ARRAY['zǐ'], ARRAY['purple'], 5, 1396),
('幕', ARRAY['mù'], ARRAY['screen'], 5, 1397),
('综', ARRAY['zōng','zèng'], ARRAY['comprehensive'], 5, 1398),
('组', ARRAY['zǔ'], ARRAY['group'], 5, 1399),
('织', ARRAY['zhī','zhì'], ARRAY['weave'], 5, 1400)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);