INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('肃', ARRAY['sù'], ARRAY['solemn'], 5, 1651),
('摇', ARRAY['yáo'], ARRAY['shake'], 5, 1652),
('辈', ARRAY['bèi'], ARRAY['generation'], 5, 1653),
('遗', ARRAY['yí','wèi'], ARRAY['legacy'], 5, 1654),
('憾', ARRAY['hàn'], ARRAY['regret'], 5, 1655),
('乙', ARRAY['yǐ'], ARRAY['second'], 5, 1656),
('亿', ARRAY['yì'], ARRAY['100 million'], 5, 1657),
('雄', ARRAY['xióng'], ARRAY['male'], 5, 1658),
('犹', ARRAY['yóu'], ARRAY['still'], 5, 1659),
('豫', ARRAY['yù'], ARRAY['yu'], 5, 1660),
('幼', ARRAY['yòu'], ARRAY['young'], 5, 1661),
('订', ARRAY['dìng'], ARRAY['order'], 5, 1662),
('玉', ARRAY['yù'], ARRAY['jade'], 5, 1663),
('摘', ARRAY['zhāi'], ARRAY['pick'], 5, 1664),
('粘', ARRAY['nián','zhān'], ARRAY['stick'], 5, 1665),
('涨', ARRAY['zhǎng','zhàng'], ARRAY['rise'], 5, 1666),
('召', ARRAY['zhào','shào'], ARRAY['summon'], 5, 1667),
('哲', ARRAY['zhé'], ARRAY['zhe'], 5, 1668),
('振', ARRAY['zhèn'], ARRAY['vibrate'], 5, 1669),
('治', ARRAY['zhì'], ARRAY['rule'], 5, 1670),
('挣', ARRAY['zhèng','zhēng'], ARRAY['earn'], 5, 1671),
('执', ARRAY['zhí'], ARRAY['execute'], 5, 1672),
('疗', ARRAY['liáo'], ARRAY['treatment'], 5, 1673),
('猪', ARRAY['zhū'], ARRAY['pig'], 5, 1674),
('渐', ARRAY['jiàn','jiān'], ARRAY['gradually'], 5, 1675),
('煮', ARRAY['zhǔ'], ARRAY['cook'], 5, 1676),
('饰', ARRAY['shì'], ARRAY['decorate'], 5, 1677),
('撞', ARRAY['zhuàng'], ARRAY['collide'], 5, 1678),
('咨', ARRAY['zī'], ARRAY['consult'], 5, 1679),
('裁', ARRAY['cái'], ARRAY['cut'], 5, 1680),
('阻', ARRAY['zǔ'], ARRAY['block'], 5, 1681),
('醉', ARRAY['zuì'], ARRAY['drunk'], 5, 1682),
('敬', ARRAY['jìng'], ARRAY['respect'], 5, 1683),
('遵', ARRAY['zūn'], ARRAY['obey'], 5, 1684),
('守', ARRAY['shǒu'], ARRAY['keep'], 5, 1685),
('挨', ARRAY['āi','ái'], ARRAY['suffer'], 6, 1686),
('癌', ARRAY['ái'], ARRAY['cancer'], 6, 1687),
('症', ARRAY['zhèng','zhēng'], ARRAY['disease'], 6, 1688),
('暧', ARRAY['ài'], ARRAY['warm'], 6, 1689),
('昧', ARRAY['mèi'], ARRAY['ambiguous'], 6, 1690),
('昂', ARRAY['áng'], ARRAY['hold head high'], 6, 1691),
('凹', ARRAY['āo','wā'], ARRAY['concave'], 6, 1692),
('凸', ARRAY['tū'], ARRAY['convex'], 6, 1693),
('奥', ARRAY['ào','yù'], ARRAY['profound'], 6, 1694),
('扒', ARRAY['bā','pá'], ARRAY['grill'], 6, 1695),
('疤', ARRAY['bā'], ARRAY['scar'], 6, 1696),
('拔', ARRAY['bá'], ARRAY['pull'], 6, 1697),
('霸', ARRAY['bà'], ARRAY['tyrant'], 6, 1698),
('罢', ARRAY['bà','ba','pí'], ARRAY['stop'], 6, 1699),
('掰', ARRAY['bāi'], ARRAY['break up'], 6, 1700)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);