INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('缴', ARRAY['jiǎo','zhuó'], ARRAY['pay'], 6, 2101),
('侥', ARRAY['jiǎo','yáo'], ARRAY['fluke'], 6, 2102),
('皆', ARRAY['jiē'], ARRAY['all'], 6, 2103),
('揭', ARRAY['jiē','qì'], ARRAY['uncover'], 6, 2104),
('奏', ARRAY['zòu'], ARRAY['play'], 6, 2105),
('杰', ARRAY['jié'], ARRAY['jay'], 6, 2106),
('晶', ARRAY['jīng'], ARRAY['crystal'], 6, 2107),
('竭', ARRAY['jié'], ARRAY['exhaust'], 6, 2108),
('截', ARRAY['jié'], ARRAY['cut'], 6, 2109),
('剖', ARRAY['pōu'], ARRAY['cut open'], 6, 2110),
('津', ARRAY['jīn'], ARRAY['tianjin'], 6, 2111),
('融', ARRAY['róng'], ARRAY['melt'], 6, 2112),
('锦', ARRAY['jǐn'], ARRAY['brocade'], 6, 2113),
('浸', ARRAY['jìn'], ARRAY['dip'], 6, 2114),
('泡', ARRAY['pào','pāo'], ARRAY['bubble'], 6, 2115),
('晋', ARRAY['jìn'], ARRAY['jin'], 6, 2116),
('茎', ARRAY['jīng'], ARRAY['stem'], 6, 2117),
('纬', ARRAY['wěi'], ARRAY['latitude'], 6, 2118),
('讶', ARRAY['yà'], ARRAY['be surprised'], 6, 2119),
('兢', ARRAY['jīng'], ARRAY['jing'], 6, 2120),
('井', ARRAY['jǐng'], ARRAY['well'], 6, 2121),
('惕', ARRAY['tì'], ARRAY['be vigilant'], 6, 2122),
('颈', ARRAY['jǐng','gěng'], ARRAY['neck'], 6, 2123),
('椎', ARRAY['zhuī','chuí'], ARRAY['vertebra'], 6, 2124),
('纠', ARRAY['jiū'], ARRAY['correct'], 6, 2125),
('鞠', ARRAY['jū'], ARRAY['ju'], 6, 2126),
('躬', ARRAY['gōng'], ARRAY['bow'], 6, 2127),
('拘', ARRAY['jū','gōu'], ARRAY['arrest'], 6, 2128),
('瞩', ARRAY['zhǔ'], ARRAY['gaze'], 6, 2129),
('咀', ARRAY['zuǐ','jǔ'], ARRAY['chew'], 6, 2130),
('嚼', ARRAY['jiáo','jué','jiào'], ARRAY['chew'], 6, 2131),
('沮', ARRAY['jǔ','jù'], ARRAY['frustrated'], 6, 2132),
('丧', ARRAY['sàng','sāng'], ARRAY['funeral'], 6, 2133),
('倔', ARRAY['juè','jué'], ARRAY['stubborn'], 6, 2134),
('君', ARRAY['jūn'], ARRAY['jun'], 6, 2135),
('辟', ARRAY['pì','bì'], ARRAY['pirate'], 6, 2136),
('拓', ARRAY['tuò','tà','zhí'], ARRAY['extend'], 6, 2137),
('刊', ARRAY['kān'], ARRAY['journal'], 6, 2138),
('勘', ARRAY['kān'], ARRAY['survey'], 6, 2139),
('探', ARRAY['tàn'], ARRAY['explore'], 6, 2140),
('侃', ARRAY['kǎn'], ARRAY['talk'], 6, 2141),
('慷', ARRAY['kāng'], ARRAY['generous'], 6, 2142),
('扛', ARRAY['káng','gāng'], ARRAY['carry'], 6, 2143),
('拢', ARRAY['lǒng'], ARRAY['gather'], 6, 2144),
('磕', ARRAY['kē'], ARRAY['knock'], 6, 2145),
('啃', ARRAY['kěn'], ARRAY['bite'], 6, 2146),
('坑', ARRAY['kēng'], ARRAY['pit'], 6, 2147),
('孔', ARRAY['kǒng'], ARRAY['hole'], 6, 2148),
('怖', ARRAY['bù'], ARRAY['terror'], 6, 2149),
('惧', ARRAY['jù'], ARRAY['fear'], 6, 2150)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);