INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('饶', ARRAY['ráo'], ARRAY['rao'], 6, 2351),
('恕', ARRAY['shù'], ARRAY['forgive'], 6, 2352),
('惹', ARRAY['rě'], ARRAY['provoke'], 6, 2353),
('祸', ARRAY['huò'], ARRAY['disaster'], 6, 2354),
('盈', ARRAY['yíng'], ARRAY['surplus'], 6, 2355),
('眶', ARRAY['kuàng'], ARRAY['orbit'], 6, 2356),
('仁', ARRAY['rén'], ARRAY['benevolence'], 6, 2357),
('溶', ARRAY['róng'], ARRAY['dissolve'], 6, 2358),
('揉', ARRAY['róu'], ARRAY['rub'], 6, 2359),
('儒', ARRAY['rú'], ARRAY['confucianism'], 6, 2360),
('若', ARRAY['ruò','rě'], ARRAY['like'], 6, 2361),
('撒', ARRAY['sā','sǎ'], ARRAY['spread'], 6, 2362),
('谎', ARRAY['huǎng'], ARRAY['lie'], 6, 2363),
('嫂', ARRAY['sǎo'], ARRAY['sister-in-law'], 6, 2364),
('啥', ARRAY['shá'], ARRAY['what'], 6, 2365),
('筛', ARRAY['shāi'], ARRAY['screen'], 6, 2366),
('烁', ARRAY['shuò'], ARRAY['sparkle'], 6, 2367),
('擅', ARRAY['shàn'], ARRAY['good at'], 6, 2368),
('筋', ARRAY['jīn'], ARRAY['tendon'], 6, 2369),
('捎', ARRAY['shāo','shào'], ARRAY['take along'], 6, 2370),
('梢', ARRAY['shāo','sào'], ARRAY['tips'], 6, 2371),
('哨', ARRAY['shào'], ARRAY['post'], 6, 2372),
('奢', ARRAY['shē'], ARRAY['extravagant'], 6, 2373),
('侈', ARRAY['chǐ'], ARRAY['extravagant'], 6, 2374),
('舌', ARRAY['shé'], ARRAY['tongue'], 6, 2375),
('氏', ARRAY['shì','zhī'], ARRAY['clan'], 6, 2376),
('绅', ARRAY['shēn'], ARRAY['gentry'], 6, 2377),
('呻', ARRAY['shēn'], ARRAY['groan'], 6, 2378),
('吟', ARRAY['yín'], ARRAY['groan'], 6, 2379),
('圣', ARRAY['shèng'], ARRAY['holy'], 6, 2380),
('仙', ARRAY['xiān'], ARRAY['fairy'], 6, 2381),
('审', ARRAY['shěn'], ARRAY['trial'], 6, 2382),
('渗', ARRAY['shèn'], ARRAY['seep'], 6, 2383),
('疏', ARRAY['shū'], ARRAY['sparse'], 6, 2384),
('肖', ARRAY['xiào','xiāo'], ARRAY['resemble'], 6, 2385),
('锈', ARRAY['xiù'], ARRAY['rust'], 6, 2386),
('牲', ARRAY['shēng'], ARRAY['sacrifice'], 6, 2387),
('畜', ARRAY['chù','xù'], ARRAY['livestock'], 6, 2388),
('尸', ARRAY['shī'], ARRAY['corpse'], 6, 2389),
('野', ARRAY['yě'], ARRAY['wild'], 6, 2390),
('逝', ARRAY['shì'], ARRAY['pass away'], 6, 2391),
('竖', ARRAY['shù'], ARRAY['vertical'], 6, 2392),
('缚', ARRAY['fù'], ARRAY['tie'], 6, 2393),
('耍', ARRAY['shuǎ'], ARRAY['play'], 6, 2394),
('衰', ARRAY['shuāi','cuī'], ARRAY['decline'], 6, 2395),
('涮', ARRAY['shuàn'], ARRAY['rinse'], 6, 2396),
('胞', ARRAY['bāo'], ARRAY['cells'], 6, 2397),
('爽', ARRAY['shuǎng'], ARRAY['cool'], 6, 2398),
('泥', ARRAY['ní','nì'], ARRAY['mud'], 6, 2399),
('瞬', ARRAY['shùn'], ARRAY['instant'], 6, 2400)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);