INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('瞒', ARRAY['mán','mén'], ARRAY['conceal'], 6, 2551),
('擎', ARRAY['qíng'], ARRAY['qing'], 6, 2552),
('婴', ARRAY['yīng'], ARRAY['infant'], 6, 2553),
('恒', ARRAY['héng'], ARRAY['constant'], 6, 2554),
('踊', ARRAY['yǒng'], ARRAY['leap'], 6, 2555),
('郁', ARRAY['yù'], ARRAY['depressed'], 6, 2556),
('腻', ARRAY['nì'], ARRAY['greasy'], 6, 2557),
('漆', ARRAY['qī'], ARRAY['paint'], 6, 2558),
('紊', ARRAY['wěn'], ARRAY['tangled'], 6, 2559),
('稚', ARRAY['zhì'], ARRAY['childish'], 6, 2560),
('诱', ARRAY['yòu'], ARRAY['lure'], 6, 2561),
('愚', ARRAY['yú'], ARRAY['stupid'], 6, 2562),
('蠢', ARRAY['chǔn'], ARRAY['stupid'], 6, 2563),
('舆', ARRAY['yú'], ARRAY['public opinion'], 6, 2564),
('渔', ARRAY['yú'], ARRAY['fish'], 6, 2565),
('绒', ARRAY['róng'], ARRAY['velvet'], 6, 2566),
('宇', ARRAY['yǔ'], ARRAY['yu'], 6, 2567),
('宙', ARRAY['zhòu'], ARRAY['universe'], 6, 2568),
('愈', ARRAY['yù'], ARRAY['heal'], 6, 2569),
('兆', ARRAY['zhào'], ARRAY['mega'], 6, 2570),
('欲', ARRAY['yù'], ARRAY['want'], 6, 2571),
('冤', ARRAY['yuān'], ARRAY['injustice'], 6, 2572),
('枉', ARRAY['wǎng'], ARRAY['in vain'], 6, 2573),
('宵', ARRAY['xiāo'], ARRAY['night'], 6, 2574),
('谱', ARRAY['pǔ'], ARRAY['spectrum'], 6, 2575),
('岳', ARRAY['yuè'], ARRAY['yue'], 6, 2576),
('熨', ARRAY['yùn','yù'], ARRAY['iron'], 6, 2577),
('蕴', ARRAY['yùn'], ARRAY['yun'], 6, 2578),
('酝', ARRAY['yùn'], ARRAY['brew'], 6, 2579),
('酿', ARRAY['niàng'], ARRAY['wine'], 6, 2580),
('砸', ARRAY['zá'], ARRAY['smash'], 6, 2581),
('咋', ARRAY['zǎ','zé','zhā'], ARRAY['what?'], 6, 2582),
('栽', ARRAY['zāi'], ARRAY['plant'], 6, 2583),
('宰', ARRAY['zǎi'], ARRAY['slaughter'], 6, 2584),
('攒', ARRAY['zǎn','cuán'], ARRAY['save'], 6, 2585),
('蹋', ARRAY['tà'], ARRAY['step on'], 6, 2586),
('遭', ARRAY['zāo'], ARRAY['suffered'], 6, 2587),
('殃', ARRAY['yāng'], ARRAY['calamity'], 6, 2588),
('噪', ARRAY['zào'], ARRAY['noise'], 6, 2589),
('贼', ARRAY['zéi'], ARRAY['thief'], 6, 2590),
('赠', ARRAY['zèng'], ARRAY['gift'], 6, 2591),
('渣', ARRAY['zhā'], ARRAY['slag'], 6, 2592),
('扎', ARRAY['zhā','zā','zhá'], ARRAY['tie'], 6, 2593),
('眨', ARRAY['zhǎ'], ARRAY['blink'], 6, 2594),
('诈', ARRAY['zhà'], ARRAY['fraud'], 6, 2595),
('债', ARRAY['zhài'], ARRAY['debt'], 6, 2596),
('券', ARRAY['quàn','xuàn'], ARRAY['coupon'], 6, 2597),
('沾', ARRAY['zhān'], ARRAY['dip'], 6, 2598),
('瞻', ARRAY['zhān'], ARRAY['look forward to'], 6, 2599),
('斩', ARRAY['zhǎn'], ARRAY['cut'], 6, 2600)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);