INSERT INTO public.characters_dict (hanzi, pinyin, meanings, hsk_level, frequency_rank) VALUES
('钉', ARRAY['dīng','dìng'], ARRAY['nail'], 6, 2601),
('崭', ARRAY['zhǎn','chán'], ARRAY['brand new'], 6, 2602),
('役', ARRAY['yì'], ARRAY['service'], 6, 2603),
('帐', ARRAY['zhàng'], ARRAY['account'], 6, 2604),
('篷', ARRAY['péng'], ARRAY['canopy'], 6, 2605),
('蓬', ARRAY['péng'], ARRAY['peng'], 6, 2606),
('沼', ARRAY['zhǎo'], ARRAY['swamp'], 6, 2607),
('泽', ARRAY['zé','shì'], ARRAY['ze'], 6, 2608),
('遮', ARRAY['zhē'], ARRAY['cover'], 6, 2609),
('稀', ARRAY['xī'], ARRAY['dilute'], 6, 2610),
('珠', ARRAY['zhū'], ARRAY['beads'], 6, 2611),
('侦', ARRAY['zhēn'], ARRAY['detect'], 6, 2612),
('斟', ARRAY['zhēn'], ARRAY['pour'], 6, 2613),
('酌', ARRAY['zhuó'], ARRAY['discretionary'], 6, 2614),
('枕', ARRAY['zhěn'], ARRAY['pillow'], 6, 2615),
('撼', ARRAY['hàn'], ARRAY['shake'], 6, 2616),
('蒸', ARRAY['zhēng'], ARRAY['steam'], 6, 2617),
('宗', ARRAY['zōng'], ARRAY['zong'], 6, 2618),
('郑', ARRAY['zhèng'], ARRAY['zheng'], 6, 2619),
('枝', ARRAY['zhī','qí'], ARRAY['branch'], 6, 2620),
('撑', ARRAY['chēng'], ARRAY['support'], 6, 2621),
('援', ARRAY['yuán'], ARRAY['aid'], 6, 2622),
('柱', ARRAY['zhù'], ARRAY['column'], 6, 2623),
('脂', ARRAY['zhī'], ARRAY['fat'], 6, 2624),
('肪', ARRAY['fáng'], ARRAY['fat'], 6, 2625),
('侄', ARRAY['zhí'], ARRAY['nephew'], 6, 2626),
('忠', ARRAY['zhōng'], ARRAY['loyal'], 6, 2627),
('央', ARRAY['yāng'], ARRAY['central'], 6, 2628),
('肿', ARRAY['zhǒng'], ARRAY['swell'], 6, 2629),
('瘤', ARRAY['liú'], ARRAY['tumor'], 6, 2630),
('州', ARRAY['zhōu'], ARRAY['state'], 6, 2631),
('舟', ARRAY['zhōu'], ARRAY['boat'], 6, 2632),
('粥', ARRAY['zhōu','yù'], ARRAY['porridge'], 6, 2633),
('皱', ARRAY['zhòu'], ARRAY['wrinkle'], 6, 2634),
('纹', ARRAY['wén','wèn'], ARRAY['pattern'], 6, 2635),
('昼', ARRAY['zhòu'], ARRAY['day'], 6, 2636),
('株', ARRAY['zhū'], ARRAY['strain'], 6, 2637),
('诸', ARRAY['zhū'], ARRAY['various'], 6, 2638),
('拄', ARRAY['zhǔ'], ARRAY['lean on'], 6, 2639),
('宅', ARRAY['zhái'], ARRAY['house'], 6, 2640),
('驻', ARRAY['zhù'], ARRAY['stationed in'], 6, 2641),
('铸', ARRAY['zhù'], ARRAY['cast'], 6, 2642),
('拽', ARRAY['zhuài','zhuāi','yè'], ARRAY['pull'], 6, 2643),
('砖', ARRAY['zhuān'], ARRAY['brick'], 6, 2644),
('卸', ARRAY['xiè'], ARRAY['unload'], 6, 2645),
('庄', ARRAY['zhuāng'], ARRAY['village'], 6, 2646),
('稼', ARRAY['jià'], ARRAY['crop'], 6, 2647),
('幢', ARRAY['zhuàng','chuáng'], ARRAY['building'], 6, 2648),
('悼', ARRAY['dào'], ARRAY['mourn'], 6, 2649),
('坠', ARRAY['zhuì'], ARRAY['fall'], 6, 2650)
ON CONFLICT (hanzi) DO UPDATE SET meanings = CASE WHEN public.characters_dict.meanings = ARRAY['—']::text[] OR array_length(public.characters_dict.meanings, 1) IS NULL THEN EXCLUDED.meanings ELSE public.characters_dict.meanings END, hsk_level = COALESCE(public.characters_dict.hsk_level, EXCLUDED.hsk_level), frequency_rank = COALESCE(public.characters_dict.frequency_rank, EXCLUDED.frequency_rank);